/* eslint-disable no-undef */
import {
  MILITES,
  CIVIS,
  RARE,
  HIDE_OPTION,
  NO_SHIELD,
  NO_ARMOUR,
  PARTIAL,
  FULL,
  SHIELD,
  HEAVY_SHIELD,
  THRUSTING,
  JAVELIN,
  SLING,
  BOW,
  AX,
  STONES,
  SWORD,
  PIKE,
  OPT_BUCKLER,
  OPT_SHIELD,
  OPT_DOWN_NO_ARMOUR,
  OPT_DOWN_PARTIAL_ARMOUR,
  OPT_UP_PARTIAL_ARMOUR,
  OPT_THROWING_OFFENSIVE,
  OPT_UP_THROWING,
  OPT_CHARGING,
  OPT_UP_SHIELD_AND_OVERLAP,
  OPT_UP_EXTRA_BOW,
  OPT_JAV_TO_BOW,
  indianElephantOptions,
  CAVALRY_SPEAR,
  OPT_UP_FULL_ARMOUR,
  BUCKLER,
  OPT_JAVELIN_SHIELD,
  XYSTON,
} from './constants';


import {
  TRAIT_IRON_WILL,
  TRAIT_SHIELD_OVERLAP,
  TRAIT_SKIRMISH_SPECIALIST,
  TRAIT_WALL_OF_SPEARS,
  TRAIT_OFFENSIVE_SPEAR,
  TRAIT_DRILLED,
  TRAIT_GUERRILLA,
  TRAIT_FUROR,
  TRAIT_ALLIES,
  TRAIT_MOUNTED,
  TRAIT_SPARABARA,
  TRAIT_IRA,
  TRAIT_FIDELIS,
  TRAIT_AIM,
  TRAIT_MARAUDERS,
  TRAIT_ELEPHANT,
  TRAIT_CHARGE,
  TRAIT_EXTRA_BOW,
  TRAIT_IMPETUS,
  TRAIT_DETERMINED,
  TRAIT_BUCKLER,
  TRAIT_ENDURANCE,
  TRAIT_SLING,
  TRAIT_EXTRA_TWO,
  TRAIT_DOUBLE,
  TRAIT_EXTRA_JAVELIN,
  TRAIT_MACEDONIAN,
} from './traits';

import {
  characters,
} from './characters';

const thraciansAndGetae = {
  ...characters,
  wildmen: {
    displayName: 'Wildmen',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: STONES,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_GUERRILLA],
    cost: 8,
    options: [
    ],
  },
  hillmen: {
    displayName: 'Hillmen',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: JAVELIN,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_GUERRILLA],
    cost: 9,
    options: [
      OPT_BUCKLER,
      OPT_JAV_TO_BOW,
    ],
  },
  tribesmen: {
    displayName: 'Tribesmen',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 5,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_GUERRILLA],
    cost: 12,
    options: [
      OPT_BUCKLER,
      OPT_JAV_TO_BOW,
    ],
  },
  spearmen: {
    displayName: 'Spearmen',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: THRUSTING,
    defaultShield: SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_EXTRA_JAVELIN, TRAIT_FUROR, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
    cost: 16,
    options: [
    ],
  },
  warriors: {
    displayName: 'Warriors',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: AX,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_FUROR, TRAIT_IRA],
    cost: 13,
    options: [
      OPT_JAVELIN_SHIELD,
    ],
  },
  nobles: {
    displayName: 'Nobles',
    availability: MILITES,
    combat: 4,
    ranged: 4,
    grit: 3,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: PARTIAL,
    traits: [TRAIT_FUROR, TRAIT_IRA, TRAIT_EXTRA_TWO],
    cost: 22,
    options: [
      OPT_JAVELIN_SHIELD,
    ],
  },
  mounted: {
    displayName: 'Mounted Warriors',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: PARTIAL,
    traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS],
    cost: 16,
    options: [
      OPT_SHIELD,
      OPT_JAV_TO_BOW,
      OPT_CHARGING,
    ],
  },
  royal: {
    displayName: 'Royal Cavalry',
    availability: MILITES,
    combat: 4,
    ranged: 4,
    grit: 3,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: PARTIAL,
    traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS],
    cost: 22,
    options: [
      OPT_DOWN_NO_ARMOUR,
      OPT_CHARGING,
    ],
  },
};
const macedonians = {
  ...characters,
  slingers: {
    displayName: 'Slingers',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: SLING,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 8,
    options: [
      OPT_BUCKLER,
    ],
  },
  bowmen: {
    displayName: 'Bowmen',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: BOW,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 8,
    options: [
      OPT_BUCKLER,
    ],
  },
  psiloi: {
    displayName: 'Psiloi',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: JAVELIN,
    defaultBody: NO_ARMOUR,
    defaultShield: NO_SHIELD,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 8,
    options: [
    ],
  },
  peltast: {
    displayName: 'Peltast',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN,
    defaultBody: NO_ARMOUR,
    defaultShield: SHIELD,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 13,
    options: [
    ],
  },
  greek: {
    displayName: 'Greek Mercenaries',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 5,
    defaultWeapon: THRUSTING,
    defaultBody: PARTIAL,
    defaultShield: HEAVY_SHIELD,
    traits: [
      TRAIT_SHIELD_OVERLAP,
      TRAIT_OFFENSIVE_SPEAR,
      TRAIT_WALL_OF_SPEARS,
      TRAIT_DRILLED,
      TRAIT_ALLIES,
    ],
    cost: 16,
    options: [
      OPT_DOWN_NO_ARMOUR,
    ],
  },
  hypaspists: {
    displayName: 'Hypaspists',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: THRUSTING,
    defaultBody: PARTIAL,
    defaultShield: HEAVY_SHIELD,
    traits: [
      TRAIT_SHIELD_OVERLAP,
      TRAIT_OFFENSIVE_SPEAR,
      TRAIT_WALL_OF_SPEARS,
      TRAIT_DRILLED,
    ],
    cost: 18,
    options: [
      OPT_UP_FULL_ARMOUR,
    ],
  },
  phalangites: {
    displayName: 'Phalangites',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: PIKE,
    defaultBody: PARTIAL,
    defaultShield: SHIELD,
    traits: [
      TRAIT_OFFENSIVE_SPEAR,
      TRAIT_WALL_OF_SPEARS,
      TRAIT_DRILLED,
      TRAIT_MACEDONIAN,
    ],
    cost: 17,
    options: [
      OPT_UP_FULL_ARMOUR,
      OPT_DOWN_NO_ARMOUR,
    ],
  },
  veteran: {
    displayName: 'Veteran Phalangites',
    availability: RARE,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: PIKE,
    defaultBody: PARTIAL,
    defaultShield: SHIELD,
    traits: [
      TRAIT_OFFENSIVE_SPEAR,
      TRAIT_WALL_OF_SPEARS,
      TRAIT_DRILLED,
      TRAIT_MACEDONIAN,
    ],
    cost: 21,
    options: [
      OPT_UP_FULL_ARMOUR,
    ],
  },
  hetairoi: {
    displayName: 'Hetairoi',
    availability: MILITES,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: XYSTON,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      TRAIT_DRILLED,
      TRAIT_CHARGE,
      TRAIT_MOUNTED,
    ],
    cost: 22,
    options: [
    ],
  },
  agema: {
    displayName: 'Agema Cavalry',
    availability: RARE,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: XYSTON,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      TRAIT_DRILLED,
      TRAIT_CHARGE,
      TRAIT_MOUNTED,
      TRAIT_DETERMINED,
    ],
    cost: 23,
    options: [
    ],
  },
  light: {
    displayName: 'Allied Light Cavalry',
    availability: RARE,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN,
    defaultBody: NO_ARMOUR,
    defaultShield: NO_SHIELD,
    traits: [
      TRAIT_MOUNTED,
      TRAIT_MARAUDERS,
      TRAIT_ALLIES,
    ],
    cost: 16,
    options: [
      OPT_SHIELD,
      OPT_UP_PARTIAL_ARMOUR,
    ],
  },
};
const galgamala = {
  eastern: {
    displayName: 'Eastern Phalangites',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 5,
    defaultWeapon: PIKE,
    defaultBody: PARTIAL,
    defaultShield: SHIELD,
    traits: [
      TRAIT_DRILLED,
      TRAIT_WALL_OF_SPEARS,
      TRAIT_OFFENSIVE_SPEAR,
      TRAIT_MACEDONIAN,
      TRAIT_ALLIES,
    ],
    cost: 15,
    options: [
      OPT_DOWN_NO_ARMOUR,
    ],
  },
  iranianCav: {
    displayName: 'Iranian Cavalry',
    availability: RARE,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN,
    defaultBody: PARTIAL,
    defaultShield: SHIELD,
    traits: [
      TRAIT_MOUNTED,
      TRAIT_ALLIES,
    ],
    cost: 18,
    options: [
      OPT_DOWN_NO_ARMOUR,
      OPT_CHARGING,
    ],
  },
  iranianHorse: {
    displayName: 'Iranian Horse Archers',
    availability: RARE,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: BOW,
    defaultBody: NO_ARMOUR,
    defaultShield: NO_SHIELD,
    traits: [
      TRAIT_MOUNTED,
      TRAIT_MARAUDERS,
      TRAIT_ALLIES,
    ],
    cost: 16,
    options: [
      OPT_BUCKLER,
    ],
  },
};
const indus = {
  elephant: {
    dontCountForBreak: true,
    displayName: 'Indian War Elephant',
    availability: RARE,
    fixedFigures: 4,
    combat: 3,
    ranged: 7,
    grit: 4,
    fixedSave: '3+',
    traits: ['attacks(3)', 'wounds(5)', TRAIT_ELEPHANT],
    cost: 18,
    options: [
    ],
    defaultWeapon: HIDE_OPTION,
    defaultShield: HIDE_OPTION,
    defaultBody: HIDE_OPTION,
  },
  elephantCrew: {
    dontCountForBreak: true,
    displayName: 'Elephant Crew',
    fixedFigures: 2,
    availability: RARE,
    traits: [TRAIT_IRON_WILL],
    cost: 16,
    options: indianElephantOptions,
    defaultWeapon: JAVELIN,
    combat: 4,
    ranged: 4,
    grit: 3,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
  },
  argyraspids: {
    displayName: 'Silver Shields',
    availability: RARE,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: THRUSTING,
    defaultBody: PARTIAL,
    defaultShield: HEAVY_SHIELD,
    traits: [
      TRAIT_DRILLED,
      TRAIT_WALL_OF_SPEARS,
      TRAIT_OFFENSIVE_SPEAR,
      TRAIT_SHIELD_OVERLAP,
      TRAIT_DETERMINED,
    ],
    cost: 23,
    options: [
      OPT_UP_FULL_ARMOUR,
    ],
  },
};

const successors = {
  thureophoroi: {
    displayName: 'Thureophoroi',
    availability: RARE,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: THRUSTING,
    defaultBody: PARTIAL,
    defaultShield: SHIELD,
    traits: [
      TRAIT_WALL_OF_SPEARS,
      TRAIT_SHIELD_OVERLAP,
      TRAIT_DETERMINED,
      TRAIT_EXTRA_JAVELIN,
    ],
    cost: 23,
    options: [
      OPT_UP_PARTIAL_ARMOUR,
    ],
  },
};

const alex = {
  Macedonian: macedonians,
  'Alexander after Galgamala': {
    ...macedonians,
    ...galgamala,
  },
  'Alexander after Indus': {
    ...macedonians,
    ...galgamala,
    ...indus,
  },
  'Alexandrian successor': {
    ...macedonians,
    ...galgamala,
    ...indus,
    ...successors,
  },
  Getae: {
    ...thraciansAndGetae,
    flaxman: {
      displayName: 'Flaxman',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: AX,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_FUROR, TRAIT_IRA],
      cost: 16,
      options: [
      ],
    },
  },
  Thracians: {
    ...thraciansAndGetae,
    mercenaries: {
      displayName: 'Thracian Mercenaries',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_FUROR, TRAIT_IRA, TRAIT_EXTRA_TWO],
      cost: 20,
      options: [
      ],
    },
  },
  Illyrians: {
    ...characters,
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    bowmen: {
      displayName: 'Bowmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    psiloi: {
      displayName: 'Psiloi',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    raiders: {
      displayName: 'Illyrian Raiders',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 11,
      options: [
        OPT_BUCKLER,
      ],
    },
    pirates: {
      displayName: 'Illyrian Pirates',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_FUROR],
      cost: 11,
      options: [
        OPT_THROWING_OFFENSIVE,
      ],
    },
    raw: {
      displayName: ' Raw Illyrian Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
      cost: 13,
      options: [
      ],
    },
    hoplites: {
      displayName: 'Illyrian Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DETERMINED],
      cost: 18,
      options: [
      ],
    },
    nobles: {
      displayName: 'Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      cost: 22,
      options: [
        OPT_DOWN_NO_ARMOUR,
        OPT_UP_FULL_ARMOUR,
        OPT_UP_THROWING,
      ],
    },
    mounted: {
      displayName: 'Mounted Nobles',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_MOUNTED, TRAIT_DETERMINED, TRAIT_FUROR],
      cost: 22,
      options: [
        OPT_DOWN_NO_ARMOUR,
        OPT_UP_FULL_ARMOUR,
      ],
    },
  },
  'Greek City States': {
    ...characters,
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    bowmen: {
      displayName: 'Bowmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    psiloi: {
      displayName: 'Psiloi',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    peltasts: {
      displayName: 'Peltasts',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 13,
      options: [
      ],
    },
    cretan: {
      displayName: 'Cretan Archers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_AIM, TRAIT_ALLIES],
      cost: 17,
      options: [
      ],
    },
    raw: {
      displayName: 'Raw Citizen Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
      cost: 13,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    citizen: {
      displayName: 'Citizen Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    mercenary: {
      displayName: 'Mercenary Hoplites',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        TRAIT_SHIELD_OVERLAP,
        TRAIT_WALL_OF_SPEARS,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_DRILLED,
        TRAIT_FIDELIS,
        TRAIT_ALLIES,
      ],
      cost: 19,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    sacred: {
      displayName: 'Sacred Band',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: [
        TRAIT_SHIELD_OVERLAP,
        TRAIT_WALL_OF_SPEARS,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_DRILLED,
        TRAIT_DETERMINED],
      cost: 24,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    thessalian: {
      displayName: 'Thessalian Style Cavalry',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED],
      cost: 20,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    hippeis: {
      displayName: 'Hippeis Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_MOUNTED],
      cost: 21,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_CHARGING,
      ],
    },
  },
  'Greek Merceneries': {
    ...characters,
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    bowmen: {
      displayName: 'Bowmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    psiloi: {
      displayName: 'Psiloi',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    peltasts: {
      displayName: 'Peltasts',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 13,
      options: [
      ],
    },
    rhodian: {
      displayName: 'Rhodesian Slingers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultShield: BUCKLER,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_SLING, TRAIT_ALLIES, TRAIT_BUCKLER],
      cost: 17,
      options: [
      ],
    },
    young: {
      displayName: 'Young Mercenary Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      cost: 14,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    seasoned: {
      displayName: 'Seasoned Mercenery Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP,
        TRAIT_WALL_OF_SPEARS,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_DRILLED,
        TRAIT_FIDELIS],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    hardened: {
      displayName: 'Hardened Mercenery Hoplites',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP,
        TRAIT_WALL_OF_SPEARS,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_DRILLED,
        TRAIT_FIDELIS],
      cost: 23,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    thracian: {
      displayName: 'Thracian Mercenaries',
      availability: RARE,
      combat: 3,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        TRAIT_FUROR,
        TRAIT_IRA,
        TRAIT_EXTRA_TWO,
        TRAIT_DOUBLE,
        TRAIT_ALLIES],
      cost: 20,
      options: [
      ],
    },
    cavalry: {
      displayName: 'Mercenary Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        TRAIT_MOUNTED,
        TRAIT_FIDELIS,
        TRAIT_ALLIES],
      cost: 21,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
        OPT_CHARGING,
      ],
    },
  },
  Persians: {
    ...characters,
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    bowmen: {
      displayName: 'Bowmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    javelin: {
      displayName: 'Takabara',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: BUCKLER,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_BUCKLER],
      cost: 9,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_ENDURANCE, TRAIT_GUERRILLA],
      cost: 8,
      options: [
      ],
    },
    spearmen: {
      displayName: 'Spearmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_OFFENSIVE_SPEAR, TRAIT_WALL_OF_SPEARS],
      cost: 9,
      options: [
      ],
    },
    sparabara: {
      displayName: 'Sparabara',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SPARABARA, TRAIT_SHIELD_OVERLAP],
      cost: 10,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    immortals: {
      displayName: 'Immortals',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_WALL_OF_SPEARS,
        TRAIT_SHIELD_OVERLAP,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_FIDELIS, TRAIT_IRA,
        TRAIT_EXTRA_BOW,
      ],
      cost: 21,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    hoplites: {
      displayName: 'Eastern hoplites',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_SHIELD_OVERLAP, TRAIT_OFFENSIVE_SPEAR],
      cost: 13,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    kardakes: {
      displayName: 'Kardakes',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        TRAIT_WALL_OF_SPEARS,
        TRAIT_SHIELD_OVERLAP,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_DRILLED,
        TRAIT_ALLIES,
      ],
      cost: 22,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    cavalry: {
      displayName: 'Persian Cavalry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED],
      cost: 15,
      options: [
        OPT_SHIELD,
        OPT_JAV_TO_BOW,
      ],
    },
    median: {
      displayName: 'Median Cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_MOUNTED],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
        OPT_JAV_TO_BOW,
        OPT_CHARGING,
      ],
    },
    scythian: {
      displayName: 'Scythian Horse Archers',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultShield: BUCKLER,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS, TRAIT_SKIRMISH_SPECIALIST, TRAIT_ALLIES],
      cost: 18,
      options: [
        OPT_CHARGING,
      ],
    },
  },
  'Steppe Nomads': {
    ...characters,
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_OFFENSIVE_SPEAR, TRAIT_WALL_OF_SPEARS],
      cost: 9,
      options: [
        OPT_UP_EXTRA_BOW,
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_OFFENSIVE_SPEAR, TRAIT_WALL_OF_SPEARS, TRAIT_EXTRA_BOW],
      cost: 14,
      options: [
      ],
    },
    riders: {
      displayName: 'Raiders',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS, TRAIT_SKIRMISH_SPECIALIST],
      cost: 15,
      options: [
        OPT_BUCKLER,
      ],
    },
    horse: {
      displayName: 'Horse Archers',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS, TRAIT_SKIRMISH_SPECIALIST],
      cost: 17,
      options: [
        OPT_BUCKLER,
        OPT_CHARGING,
      ],
    },
    nobles: {
      displayName: 'Noble Riders',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_EXTRA_BOW],
      cost: 25,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    amazons: {
      displayName: 'Amazons',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS, TRAIT_DETERMINED, TRAIT_SKIRMISH_SPECIALIST],
      cost: 22,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    lancers: {
      displayName: 'Lancers',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultBody: FULL,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_CHARGE, TRAIT_FIDELIS, TRAIT_EXTRA_BOW],
      cost: 27,
      options: [
      ],
    },
  },
  Indian: {
    ...characters,
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    bowmen: {
      displayName: 'Bowmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    spearmen: {
      displayName: 'Spearmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_OFFENSIVE_SPEAR, TRAIT_WALL_OF_SPEARS],
      cost: 11,
      options: [
        OPT_UP_SHIELD_AND_OVERLAP,
      ],
    },
    forest: {
      displayName: 'Forest Indians',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_GUERRILLA, TRAIT_AIM],
      cost: 14,
      options: [
      ],
    },
    nobles: {
      displayName: 'Noble Warriors',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [TRAIT_OFFENSIVE_SPEAR, TRAIT_WALL_OF_SPEARS],
      cost: 14,
      options: [
        OPT_UP_SHIELD_AND_OVERLAP,
      ],
    },
    clubmen: {
      displayName: 'Two Handed Swordmen/Clubmen',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: AX,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_FUROR, TRAIT_IRA],
      cost: 17,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    maiden: {
      displayName: 'Maiden Guard',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_OFFENSIVE_SPEAR, TRAIT_WALL_OF_SPEARS, TRAIT_FIDELIS],
      cost: 18,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
        OPT_UP_SHIELD_AND_OVERLAP,
      ],
    },
    cavalry: {
      displayName: 'Cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED],
      cost: 16,
      options: [
        OPT_CHARGING,
      ],
    },
    elephant: {
      dontCountForBreak: true,
      displayName: 'Indian War Elephant',
      availability: RARE,
      fixedFigures: 5,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: '3+',
      traits: ['attacks(3)', 'wounds(5)', TRAIT_ELEPHANT],
      cost: 14.4,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      dontCountForBreak: true,
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_IRON_WILL],
      cost: 18,
      options: indianElephantOptions,
    },
  },

};

export default alex;
