import {
  mageOptions,
  characterOptions,
  NO_SHIELD,
  NO_ARMOUR,
  FULL,
  SHIELD,
  SWORD,
} from './constants';

import traits from './traits';

export const mages = {
  archmage: {
    dontCountForBreak: true,
    isCharacter: true,
    fixedFigures: 1,
    displayName: 'Archmage',
    availability: 'character',
    cost: 134,
    options: mageOptions,
    defaultWeapon: SWORD,
    combat: 4,
    ranged: 5,
    grit: 3,
    commandRange: 8,
    commandPoints: 2,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['wounds(3)', traits.IRON_WILL, traits.ARCANIST_3],
  },
  mage: {
    dontCountForBreak: true,
    isCharacter: true,
    fixedFigures: 1,
    displayName: 'Mage',
    availability: 'character',
    cost: 89,
    options: mageOptions,
    defaultWeapon: SWORD,
    combat: 4,
    ranged: 5,
    grit: 3,
    commandRange: 8,
    commandPoints: 2,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['wounds(2)', traits.IRON_WILL, traits.ARCANIST_2],
  },
  apprentice: {
    dontCountForBreak: true,
    isCharacter: true,
    fixedFigures: 1,
    displayName: 'Apprentice',
    availability: 'character',
    cost: 46,
    options: mageOptions,
    defaultWeapon: SWORD,
    combat: 4,
    ranged: 5,
    grit: 3,
    commandRange: 0,
    commandPoints: 0,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['wounds(2)', traits.IRON_WILL, traits.ARCANIST_1, traits.INDEPENDENT],
  },
};

export const warlord = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Warlord',
  availability: 'character',
  cost: 151,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 5,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(3)', 'wounds(3)', traits.IRON_WILL, traits.DVERGR],
};
export const lord = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Lord',
  availability: 'character',
  cost: 121,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 4,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', 'wounds(3)', traits.IRON_WILL, traits.DVERGR],
};
export const hero = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Hero',
  availability: 'character',
  cost: 91,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 3,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', 'wounds(2)', traits.IRON_WILL, traits.DVERGR],
};
export const champion = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Champion',
  availability: 'character',
  cost: 61,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 3,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', traits.IRON_WILL, traits.DVERGR],
};
export const sorcerer = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Sorcerer',
  availability: 'character',
  cost: 89,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 2,
  defaultShield: NO_SHIELD,
  defaultBody: NO_ARMOUR,
  traits: ['wounds(2)', 'attacks(2)', traits.IRON_WILL, traits.ARCANIST_2, traits.DVERGR],
};
export const deathLord = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Death Lord',
  availability: 'character',
  cost: 153,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 5,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(3)', 'wounds(3)', 'Controller(10)', traits.UNDEAD],
};
export const charnelWarrior = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Charnel Warrior',
  availability: 'character',
  cost: 123,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 4,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', 'wounds(3)', 'Controller(10)', traits.UNDEAD],
};
export const eldark = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Eldark',
  availability: 'character',
  cost: 93,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 3,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', 'wounds(2)', 'Controller(10)', traits.UNDEAD],
};
export const skogarmadr = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Skogarmadr',
  availability: 'character',
  cost: 63,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 3,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['wounds(2)', 'Controller(10)', traits.UNDEAD],
};
export const necrach = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Necrach',
  availability: 'character',
  cost: 136,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 2,
  defaultShield: NO_SHIELD,
  defaultBody: NO_ARMOUR,
  traits: ['wounds(3)', 'Controller(10)', traits.ARCANIST_2, traits.UNDEAD],
};
export const undeadSorcerer = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Sorcerer',
  availability: 'character',
  cost: 91,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 2,
  defaultShield: NO_SHIELD,
  defaultBody: NO_ARMOUR,
  traits: ['wounds(2)', 'Controller(10)', traits.ARCANIST_2, traits.UNDEAD],
};
export const consul = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Consul',
  availability: 'character',
  cost: 183,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 5,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['wounds(3)', 'attacks(3)', 'Controller(10)', traits.ARCANIST_2, traits.UNDEAD],
};
export const centurion = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Centurion',
  availability: 'character',
  cost: 123,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 4,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['wounds(3)', 'attacks(2)', 'Controller(10)', traits.UNDEAD],
};
export const optio = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Optio',
  availability: 'character',
  cost: 93,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 3,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['wounds(2)', 'attacks(2)', 'Controller(10)', traits.UNDEAD],
};
export const prince = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Prince',
  availability: 'character',
  cost: 152,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 5,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(3)', 'wounds(3)', traits.IRON_WILL, traits.PRIDE],
};
export const kinlord = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Kinlord',
  availability: 'character',
  cost: 122,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 4,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', 'wounds(3)', traits.IRON_WILL, traits.PRIDE],
};
export const earl = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Earl',
  availability: 'character',
  cost: 92,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 3,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', 'wounds(2)', traits.IRON_WILL, traits.PRIDE],
};
export const kinthane = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Kinthane',
  availability: 'character',
  cost: 62,
  options: characterOptions,
  defaultWeapon: SWORD,
  combat: 3,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 3,
  defaultShield: SHIELD,
  defaultBody: FULL,
  traits: ['attacks(2)', traits.IRON_WILL, traits.PRIDE],
};
export const elvenMage = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Elven Mage',
  availability: 'character',
  cost: 165,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  commandRange: 8,
  commandPoints: 2,
  defaultShield: NO_SHIELD,
  defaultBody: NO_ARMOUR,
  traits: ['wounds(3)', traits.IRON_WILL, traits.ARCANIST_3, traits.PRIDE],
};
export const wiseWizard = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Wise Wizard',
  availability: 'character',
  cost: 179,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 5,
  defaultShield: NO_SHIELD,
  defaultBody: NO_ARMOUR,
  traits: ['wounds(3)', traits.IRON_WILL, traits.ARCANIST_3],
};
export const cunningWizard = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Cunning Wizard',
  availability: 'character',
  cost: 179,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  commandRange: 10,
  commandPoints: 5,
  defaultShield: NO_SHIELD,
  defaultBody: NO_ARMOUR,
  traits: ['wounds(3)', traits.IRON_WILL, traits.ARCANIST_3],
};
export const orcShaman = {
  dontCountForBreak: true,
  isCharacter: true,
  fixedFigures: 1,
  displayName: 'Orc Shaman',
  availability: 'character',
  cost: 46,
  options: mageOptions,
  defaultWeapon: SWORD,
  combat: 4,
  ranged: 5,
  grit: 3,
  defaultShield: NO_SHIELD,
  defaultBody: NO_ARMOUR,
  traits: ['wounds(2)', traits.IRON_WILL, traits.INDEPENDENT, traits.ARCANIST_1],
};
