import {
  MILITES,
  CIVIS,
  RARE,
  XBOW,
  PARTIAL,
  SHIELD,
  PIKE,
  NO_SHIELD,
  JAVELIN,
  ARQUEBUS,
  ENCLOSED,
  SWORD,
  HEAVY_LANCE,
  BARDING,
  NO_ARMOUR,
  OPT_UP_FULL_ARMOUR,
  OPT_DOWN_NO_ARMOUR,
  OPT_UP_TEMPERED_STEEL,
  OPT_UP_HEAVY_WEAPON,
  OPT_EXTRA_MACE,
  OPT_UP_PARTIAL_ARMOUR,
  OPT_UP_SHIELD,
  OPT_UP_PIKE,
  OPT_OP_ZWEIHANDER,
  OPT_OP_INDEPENDENT,
  FULL,
  BOW,
  THRUSTING,
  LIGHT_LANCE,
} from './constants';

import traits from './traits';

import {
  condCharacters,
} from './characters';

const condottieri = {
  Spanish: {
    ...condCharacters,
    xbow: {
      displayName: 'Crossbowmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    ltCav: {
      displayName: 'Light Cavalry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED,
        traits.MARAUDERS,
      ],
      cost: 17,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    militiaPike: {
      displayName: 'Militia Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.PIKE_ATTACK,
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
      ],
    },
    pike: {
      displayName: 'Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.PIKE_ATTACK,
        traits.DRILLED,
      ],
      cost: 14,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    arquebus: {
      displayName: 'Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 22,
      options: [
        OPT_EXTRA_MACE,
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    mounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
        traits.UNRELIABLE,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsPike: {
      displayName: 'Landsknecht Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.UNRELIABLE,
        traits.BRACE,
      ],
      cost: 14,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    spanishMAA: {
      displayName: 'Spanish men at arms',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.CHARGE,
        traits.UNRELIABLE,
      ],
      cost: 20,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    swordAndBuckler: {
      displayName: 'Sword and Buckler',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: SWORD,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.DETERMINED,
        traits.SWORDSMAN,
      ],
      cost: 15,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    guardias: {
      displayName: 'Guardias de Castilla',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: SHIELD,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      traits: [
        traits.DESTRIER,
        traits.DUTY,
        traits.EXTRA_MACE,
      ],
      cost: 27,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    vetItalianMountedXbow: {
      displayName: 'Veteran Italian Mounted Crossbow',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.MARAUDERS,
        traits.UNRELIABLE,
      ],
      cost: 19,
      options: [
      ],
    },
  },
  'Holy Roman Empire': {
    ...condCharacters,
    landsArquebus: {
      displayName: 'Landsknecht Arquebus',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsCrossbow: {
      displayName: 'Landsknecht Crossbow',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsPike: {
      displayName: 'Landsknecht Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
      ],
      cost: 14,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    militiaSpear: {
      displayName: 'Militia Spear',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.PIKE_ATTACK,
        traits.UNRELIABLE,
        traits.OFFENSIVE_SPEAR,
      ],
      cost: 8,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
        OPT_UP_PIKE,
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_SHIELD,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 10,
      options: [
      ],
    },
    mAA: {
      displayName: 'Men at arms',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.EXTRA_MACE,
        traits.CHARGE,
      ],
      cost: 24,
      options: [
        OPT_EXTRA_MACE,
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    mounted_xbow: {
      displayName: 'Mounted Crossbows',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
      ],
    },
    poorMAA: {
      displayName: 'Poorly equipped Men at arms',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: FULL,
      traits: [
        traits.MOUNTED,
        traits.CHARGE,
      ],
      cost: 20,
      options: [
        OPT_EXTRA_MACE,
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    trainedMilitia: {
      displayName: 'Trained Militia',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 1,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    eliteMAA: {
      displayName: 'Elite Men at arms',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.BARDING,
        traits.MOUNTED,
        traits.EXTRA_MACE,
        traits.CHARGE,
        traits.DESTRIER,
        traits.NOBLE_DISDAIN,
      ],
      cost: 28,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    italianArquebus: {
      displayName: 'Italian Arquebus',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
        traits.MOUNTED_INFANTRY,
      ],
      cost: 15,
      options: [
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 20,
      options: [
        OPT_EXTRA_MACE,
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    italianMounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
        traits.UNRELIABLE,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    mounted_arquebus: {
      displayName: 'Mounted Arquebus',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
      ],
    },
  },
  'Venice Early': {
    ...condCharacters,
    italianMounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    arquebus: {
      displayName: 'Mercenary Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    xbow: {
      displayName: 'Mercenary Crossbowmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    pike: {
      displayName: 'Mercenary Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.PIKE_ATTACK,
        traits.DRILLED,
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_OP_ZWEIHANDER,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    militia: {
      displayName: 'Militia',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 9,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    stradiots: {
      displayName: 'Stradiots',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_OP_INDEPENDENT,
      ],
    },
    elmeti: {
      displayName: 'Elmeti',
      availability: CIVIS,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      traits: [
        traits.DESTRIER,
        traits.EXTRA_MACE,
      ],
      cost: 31,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 22,
      options: [
        OPT_EXTRA_MACE,
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    mounted_arquebus: {
      displayName: 'Italian Mounted Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsArquebus: {
      displayName: 'Landsknecht Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsCrossbow: {
      displayName: 'Landsknecht Crossbow',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsPike: {
      displayName: 'Landsknecht Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    militiaPike: {
      displayName: 'Militia Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 7,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
  },
  'Venice Late': {
    ...condCharacters,
    arquebus: {
      displayName: 'Mercenary Arquebus',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    xbow: {
      displayName: 'Mercenary Crossbowmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    pike: {
      displayName: 'Mercenary Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.PIKE_ATTACK,
        traits.DRILLED,
        traits.UNRELIABLE,
        traits.BRACE,
      ],
      cost: 13,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_OP_ZWEIHANDER,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    militia: {
      displayName: 'Militia',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.DETERMINED,
      ],
      cost: 13,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    militiaPike: {
      displayName: 'Militia Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.DETERMINED,
      ],
      cost: 11,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    stradiots: {
      displayName: 'Stradiots',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_OP_INDEPENDENT,
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 22,
      options: [
        OPT_EXTRA_MACE,
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    italianMounted_arquebus: {
      displayName: 'Italian Mounted Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    italianMounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsArquebus: {
      displayName: 'Landsknecht Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsCrossbow: {
      displayName: 'Landsknecht Crossbow',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsPike: {
      displayName: 'Landsknecht Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vetPike: {
      displayName: 'Veteran Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.DETERMINED,
        traits.BRACE,
      ],
      cost: 14,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    elmeti: {
      displayName: 'Elmeti',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      traits: [
        traits.DESTRIER,
        traits.EXTRA_MACE,
      ],
      cost: 31,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    swissArquebus: {
      displayName: 'Swiss Arquebus',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    swissCrossbow: {
      displayName: 'Swiss Crossbow',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    swissPike: {
      displayName: 'Swiss Pike',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.RUTHLESS,
      ],
      cost: 18,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
        OPT_OP_ZWEIHANDER,
      ],
    },
  },
  'French Early': {
    ...condCharacters,
    swissPike: {
      displayName: 'Swiss Pike',
      availability: CIVIS,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.RUTHLESS,
      ],
      cost: 19,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
        OPT_OP_ZWEIHANDER,
      ],
    },
    swissCrossbow: {
      displayName: 'Swiss Crossbow',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    swissArquebus: {
      displayName: 'Swiss Arquebus',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    italianMounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 22,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    frenchCrossbow: {
      displayName: 'French Crossbow',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    frenchMAA: {
      displayName: 'French men at arms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: FULL,
      traits: [
        traits.MOUNTED,
        traits.DUTY,
      ],
      cost: 21,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    vetSwissPike: {
      displayName: 'Veteran Swiss Pike',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.RUTHLESS,
      ],
      cost: 21,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
        OPT_OP_ZWEIHANDER,
      ],
    },
    vetSwissCrossbow: {
      displayName: 'Veteran Swiss Crossbow',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.BAD_WAR,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vetSwissArquebus: {
      displayName: 'Veteran Swiss Arquebus',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.BAD_WAR,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vetMounted_xbow: {
      displayName: 'Veteran Italian Mounted Crossbows',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
        traits.SKIRMISH_SPECIALIST,
        traits.MARAUDERS,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    gendarmes: {
      displayName: 'Gendarmes',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      traits: [
        traits.MOUNTED,
        traits.DUTY,
        traits.DESTRIER,
        traits.NOBLE_DISDAIN,
        traits.CHARGE,
        traits.EXTRA_MACE,
      ],
      cost: 34,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
  },
  'French Late': {
    ...condCharacters,
    frenchArquebus: {
      displayName: 'French Arquebus',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    frenchCrossbow: {
      displayName: 'French Crossbow',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    frenchFoot: {
      displayName: 'French Light Foot',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 12,
      options: [
      ],
    },
    frenchPike: {
      displayName: 'French Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 12,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
      ],
    },
    frenchMAA: {
      displayName: 'French men at arms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: FULL,
      traits: [
        traits.MOUNTED,
        traits.DUTY,
      ],
      cost: 21,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
        traits.UNRELIABLE,
      ],
      cost: 22,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    mounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
        traits.MOUNTED,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    swissPike: {
      displayName: 'Swiss Pike',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.RUTHLESS,
      ],
      cost: 19,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
        OPT_OP_ZWEIHANDER,
      ],
    },
    swissCrossbow: {
      displayName: 'Swiss Crossbow',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    swissArquebus: {
      displayName: 'Swiss Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    gendarmes: {
      displayName: 'Gendarmes',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      traits: [
        traits.MOUNTED,
        traits.DUTY,
        traits.DESTRIER,
        traits.NOBLE_DISDAIN,
        traits.CHARGE,
        traits.EXTRA_MACE,
      ],
      cost: 34,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
    vetMounted_xbow: {
      displayName: 'Veteran Italian Mounted Crossbows',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
        traits.SKIRMISH_SPECIALIST,
        traits.MARAUDERS,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vetSwissCrossbow: {
      displayName: 'Veteran Swiss Crossbow',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.BAD_WAR,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vetSwissArquebus: {
      displayName: 'Veteran Swiss Arquebus',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.BAD_WAR,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
  },
  'Italian States Early': {
    ...condCharacters,
    crossbow: {
      displayName: 'Crossbow',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    mounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    arquebus: {
      displayName: 'Mercenary Arquebus',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    xbow: {
      displayName: 'Mercenary Crossbowmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    pike: {
      displayName: 'Mercenary Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.PIKE_ATTACK,
        traits.DRILLED,
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_OP_ZWEIHANDER,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    militia: {
      displayName: 'Militia',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 9,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
      ],
      cost: 23,
      options: [
        OPT_UP_TEMPERED_STEEL,
        OPT_EXTRA_MACE,
      ],
    },
    mounted_arquebus: {
      displayName: 'Italian Mounted Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsArquebus: {
      displayName: 'Landsknecht Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsCrossbow: {
      displayName: 'Landsknecht Crossbow',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsPike: {
      displayName: 'Landsknecht Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vetMounted_xbow: {
      displayName: 'Veteran Italian Mounted Crossbows',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
        traits.SKIRMISH_SPECIALIST,
        traits.MARAUDERS,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    elmeti: {
      displayName: 'Elmeti',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      traits: [
        traits.DESTRIER,
        traits.EXTRA_MACE,
      ],
      cost: 31,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
  },
  'Italian States Late': {
    ...condCharacters,
    crossbow: {
      displayName: 'Crossbow',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    mounted_xbow: {
      displayName: 'Italian Mounted Crossbows',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    arquebus: {
      displayName: 'Mercenary Arquebus',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    xbow: {
      displayName: 'Mercenary Crossbowmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    pike: {
      displayName: 'Mercenary Pike',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.PIKE_ATTACK,
        traits.DRILLED,
        traits.UNRELIABLE,
      ],
      cost: 13,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    militia: {
      displayName: 'Militia',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.UNRELIABLE,
      ],
      cost: 9,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    italianMAA: {
      displayName: 'Italian men at arms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      traits: [
        traits.MOUNTED,
      ],
      cost: 23,
      options: [
        OPT_UP_TEMPERED_STEEL,
        OPT_EXTRA_MACE,
      ],
    },
    mounted_arquebus: {
      displayName: 'Italian Mounted Arquebus',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsCrossbow: {
      displayName: 'Landsknecht Crossbow',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.BAD_WAR,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    landsPike: {
      displayName: 'Landsknecht Pike',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.DRILLED,
        traits.PIKE_ATTACK,
        traits.BAD_WAR,
        traits.BRACE,
        traits.UNRELIABLE,
      ],
      cost: 14,
      options: [
        OPT_UP_HEAVY_WEAPON,
        OPT_UP_FULL_ARMOUR,
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vetMounted_xbow: {
      displayName: 'Veteran Italian Mounted Crossbows',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED_INFANTRY,
        traits.SKIRMISH_SPECIALIST,
        traits.MARAUDERS,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    elmeti: {
      displayName: 'Elmeti',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_LANCE,
      defaultShield: NO_SHIELD,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      traits: [
        traits.DESTRIER,
        traits.EXTRA_MACE,
      ],
      cost: 31,
      options: [
        OPT_UP_TEMPERED_STEEL,
      ],
    },
  },
};

export default condottieri;
