/* eslint-disable no-undef */
import {
  MILITES,
  CIVIS,
  RARE,
  HIDE_OPTION,
  NO_SHIELD,
  NO_ARMOUR,
  PARTIAL,
  PARTIAL_IMPROVED,
  SHIELD,
  HEAVY_SHIELD,
  THROWING,
  CAVALRY_SPEAR,
  JAVELIN,
  SLING,
  BOW,
  SCORPIO,
  elephantOptions,
  FULL,
  AX,
  KONTOS,
  ADDITIONAL,
  BARDING,
  ENCLOSED,
  XYSTON,
  THRUSTING,
  OPT_DOWN_NO_ARMOUR,
  OPT_DOWN_NO_SHIELD,
  OPT_UP_IMPROVED_FULL_ARMOUR,
  OPT_UP_FULL_ARMOUR,
  OPT_UPGRADE_EXTRA_BOW,
  OPT_DOWN_HALF_BARDING,
  OPT_DOWN_FULL_TO_NO_BARDING,
  OPT_DOWN_FULL_TO_NO_ARMOUR,
  PIKE,
  MIXED,
  OPT_SHIELD,
  SWORD,
  OPT_BUCKLER,
  OPT_DOWN_PARTIAL_ARMOUR,
  OPT_UP_HEAVY_SHIELD,
  OPT_DOWN_HEAVY_SHIELD,
  OPT_UP_PARTIAL_ARMOUR,
  OPT_NOT_POORLY,
  OPT_UP_SHIELD,
  OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
  OPT_UP_SHIELD_EXTRA,
} from './constants';

import traits from './traits';

import {
  characters,
  charactersWithChariots,
  charactersWithFamilies,
  chariotRider,
  charioteer,
} from './characters';


const eagles = {
  'Late Republican Roman': {
    ...characters,
    slack: {
      displayName: 'Slack legionaries',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
        traits.IMPULSUM,
      ],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    trained: {
      displayName: 'Trained legionaries',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
        traits.IMPULSUM,
      ],
      cost: 22,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Veteran legionaries',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
        traits.IMPULSUM,
        traits.GRIZZLED,
      ],
      cost: 25,
      options: [
      ],
    },
    iberian: {
      displayName: 'Iberian allied infantry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.GUERRILLA,
        traits.DETERMINED,
        traits.ALLIES,
      ],
      cost: 17,
      options: [
      ],
    },
    gallic: {
      displayName: 'Gallic or Glatian allied infantry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.FUROR,
        traits.ALLIES,
      ],
      cost: 17,
      options: [
      ],
    },
    javelin: {
      displayName: 'Allied javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 9,
      options: [
        OPT_DOWN_NO_SHIELD,
      ],
    },
    slingers: {
      displayName: 'Allied slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 8,
      options: [
      ],
    },
    cavalry: {
      displayName: 'Iberian/Gallic/Glatian cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED,
        traits.IMPETUS,
        traits.ALLIES,
        traits.EXTRA_JAVELIN,
      ],
      cost: 25,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    cretan: {
      displayName: 'Cretan archers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.AIM,
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
    numidian: {
      displayName: 'Numidian or other light cavalry',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.MOUNTED,
        traits.ALLIES,
        traits.MARAUDERS],
      cost: 17,
      options: [
      ],
    },

    elephant: {
      dontCountForBreak: true,
      displayName: 'African Forest Elephant',
      availability: RARE,
      fixedFigures: 4,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: '3+',
      traits: ['attacks(4)', 'wounds(4)', traits.ELEPHANT],
      cost: 16.5,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      dontCountForBreak: true,
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: RARE,
      traits: [traits.IRON_WILL],
      cost: 18,
      options: elephantOptions,
      defaultWeapon: JAVELIN,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
    },
    scorpio: {
      displayName: 'Scorpio',
      fixedFigures: 6,
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SCORPIO,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.AIM,
        traits.SKIRMISH_SPECIALIST,
        traits.IRON_WILL,
      ],
      cost: 11,
      options: [
      ],
    },
  },
  'Early Imperial Roman': {
    ...characters,
    slack: {
      displayName: 'Slack legionaries',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL_IMPROVED,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
        traits.IMPULSUM,
      ],
      cost: 21,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    trained: {
      displayName: 'Trained legionaries',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL_IMPROVED,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
        traits.IMPULSUM,
      ],
      cost: 23,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_UP_IMPROVED_FULL_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Veteran legionaries',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL_IMPROVED,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
        traits.IMPULSUM,
        traits.GRIZZLED,
      ],
      cost: 26,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_UP_IMPROVED_FULL_ARMOUR,
      ],
    },
    auxilia: {
      displayName: 'Auxiliary infantry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
      ],
      cost: 18,
      options: [
      ],
    },
    aux_archers: {
      displayName: 'Auxiliary archers',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.OVERHEAD,
      ],
      cost: 14,
      options: [
      ],
    },
    allied_archers: {
      displayName: 'Allied archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 8,
      options: [
      ],
    },
    allied_javelin: {
      displayName: 'Allied javelinmen',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NONE,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 9,
      options: [
      ],
    },
    cavalry: {
      displayName: 'Auxiliary Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [
        traits.MOUNTED,
        traits.IMPETUS,
        traits.EXTRA_JAVELIN,
      ],
      cost: 24,
      options: [
      ],
    },
    equites: {
      displayName: 'Equites Sagitarii',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: FULL,
      traits: [
        traits.MOUNTED,
      ],
      cost: 18,
      options: [
      ],
    },
    scorpio: {
      displayName: 'Scorpio',
      fixedFigures: 6,
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SCORPIO,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL_IMPROVED,
      traits: [
        traits.AIM,
        traits.SKIRMISH_SPECIALIST,
        traits.IRON_WILL,
      ],
      cost: 11.3,
      options: [
      ],
    },
  },
  'Ancient British': {
    ...charactersWithChariots(),
    chariotRider,
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 9,
      options: [
        OPT_DOWN_NO_SHIELD,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.WALL_OF_SPEARS, traits.POORLY],
      cost: 9,
      options: [
        OPT_UP_HEAVY_SHIELD,
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.GUERRILLA,
        traits.BUSHMASTER],
      cost: 17,
      options: [
        OPT_DOWN_HEAVY_SHIELD,
      ],
    },
    lowland: {
      displayName: 'Allied lowland celts',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SHIELD_OVERLAP,
        traits.WALL_OF_SPEARS,
        traits.FUROR,
        traits.ALLIES],
      cost: 17,
      options: [
      ],
    },
    nobles: {
      displayName: 'Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.BUSHMASTER,
        traits.GUERRILLA],
      cost: 21,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
        OPT_DOWN_HEAVY_SHIELD,
      ],
    },
    fanatics: {
      displayName: 'Fanatics',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.IRA,
        traits.GUERRILLA,
        traits.BUSHMASTER,
      ],
      cost: 20,
      options: [
        OPT_DOWN_HEAVY_SHIELD,
      ],
    },
    mounted: {
      displayName: 'Light cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED],
      cost: 16,
      options: [
      ],
    },
    dogs: {
      displayName: 'British Mastiffs',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.FERAL],
      cost: 10,
      options: [
      ],
    },
  },
  Dacians: {
    ...characters,
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 9,
      options: [
        OPT_DOWN_NO_SHIELD,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.WALL_OF_SPEARS],
      cost: 13,
      options: [
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.VICIOUS],
      cost: 17,
      options: [
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
      ],
    },
    nobles: {
      displayName: 'Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.VICIOUS],
      cost: 23,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    falxmen: {
      displayName: 'Falxmen',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: AX,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.LINE_BREAKER,
      ],
      cost: 14,
      options: [
      ],
    },
    light_cav: {
      displayName: 'Light cavalry',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED],
      cost: 16,
      options: [
      ],
    },
    mounted_archers: {
      displayName: 'Allied mounted archers',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED, traits.ALLIES],
      cost: 15,
      options: [
      ],
    },
    sarmatian: {
      displayName: 'Allied Sarmatian Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: KONTOS,
      defaultBarding: BARDING,
      defaultShield: NO_SHIELD,
      defaultBody: FULL,
      traits: [traits.MOUNTED, traits.CHARGE, traits.ALLIES],
      cost: 24,
      options: [
        OPT_UPGRADE_EXTRA_BOW,
        OPT_DOWN_HALF_BARDING,
        OPT_DOWN_FULL_TO_NO_BARDING,
      ],
    },
    scorpio: {
      displayName: 'Scorpio',
      fixedFigures: 6,
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SCORPIO,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.AIM,
        traits.SKIRMISH_SPECIALIST,
        traits.IRON_WILL,
      ],
      cost: 11,
      options: [
      ],
    },
  },
  'Plains Germans': {
    ...charactersWithFamilies(),
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_UP_SHIELD,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.WALL_OF_SPEARS, traits.POORLY],
      cost: 14,
      options: [
        OPT_NOT_POORLY,
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.POORLY,
        traits.ROBUR,
      ],
      cost: 16,
      options: [
        OPT_NOT_POORLY,
      ],
    },
    allied: {
      displayName: 'Allied Forest Tribe Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.GUERRILLA,
        traits.POORLY,
        traits.ROBUR,
        traits.ALLIES,
      ],
      cost: 16,
      options: [
      ],
    },
    veteran: {
      displayName: 'Veteran Warriors',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.ROBUR,
      ],
      cost: 21,
      options: [
      ],
    },
    mounted: {
      displayName: 'Cavalry',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.MOUNTED,
        traits.IMPETUS,
        traits.ROBUR,
        traits.EXTRA_JAVELIN,
      ],
      cost: 24,
      options: [
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
      ],
    },
    fanatics: {
      displayName: 'Fanatics',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.IRA,
        traits.ROBUR,
        traits.POORLY,
      ],
      cost: 19,
      options: [
        OPT_NOT_POORLY,
      ],
    },
  },
  'Forest Germans': {
    ...charactersWithFamilies(),
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.WALL_OF_SPEARS, traits.POORLY],
      cost: 14,
      options: [
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.GUERRILLA,
        traits.POORLY,
        traits.ROBUR,
      ],
      cost: 16,
      options: [
        OPT_NOT_POORLY,
      ],
    },
    allied: {
      displayName: 'Allied Plains Tribes Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SHIELD_OVERLAP,
        traits.WALL_OF_SPEARS,
        traits.ROBUR,
        traits.POORLY,
        traits.ALLIES,
      ],
      cost: 16,
      options: [
        OPT_NOT_POORLY,
      ],
    },
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_UP_SHIELD,
      ],
    },
    veteran: {
      displayName: 'Veteran Warriors',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.GUERRILLA,
        traits.ROBUR,
      ],
      cost: 21,
      options: [
      ],
    },
    romanized: {
      displayName: 'Romanized Warriors',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
      ],
      cost: 18,
      options: [
      ],
    },
    mounted: {
      displayName: 'Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.MOUNTED,
        traits.IMPETUS,
        traits.ROBUR,
        traits.EXTRA_JAVELIN,
      ],
      cost: 24,
      options: [
      ],
    },
    fanatics: {
      displayName: 'Fanatics',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.IRA,
        traits.ROBUR,
        traits.POORLY,
      ],
      cost: 19,
      options: [
        OPT_NOT_POORLY,
      ],
    },
  },
  Parthian: {
    ...characters,
    horse: {
      displayName: 'Horse Archers',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.MOUNTED],
      cost: 15,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [],
      cost: 10,
      options: [
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 8,
      options: [
      ],
    },
    javelinmen: {
      displayName: 'Javelin men',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 9,
      options: [
      ],
    },
    cataphracts: {
      displayName: 'Cataphracts',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: KONTOS,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.CHARGE,
      ],
      cost: 26,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    militia: {
      displayName: 'Militia',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
      ],
      cost: 12,
      options: [
      ],
    },
  },

  Pontic: {
    ...characters,
    charioteer,
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
      ],
    },
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.WALL_OF_SPEARS],
      cost: 13,
      options: [
      ],
    },
    phalangites: {
      displayName: 'Phalangites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.OFFENSIVE_SPEAR,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.MACEDONIAN,
      ],
      cost: 17,
      options: [
      ],
    },
    thureophoroi: {
      displayName: 'Thureophoroi',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.EXTRA_JAVELIN, traits.WALL_OF_SPEARS, traits.OFFENSIVE_SPEAR],
      cost: 16,
      options: [
      ],
    },
    romanized: {
      displayName: 'Romanized Infantry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
      ],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    vet_phalangites: {
      displayName: 'Veteran Phalangites',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.OFFENSIVE_SPEAR,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.MACEDONIAN,
      ],
      cost: 21,
      options: [
      ],
    },
    vet_romanized: {
      displayName: 'Veteran Romanized Infantry',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
      ],
      cost: 23,
      options: [
      ],
    },
    noble_cav: {
      displayName: 'Noble Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.MOUNTED,
        traits.EXTRA_JAVELIN,
        traits.IMPETUS,
      ],
      cost: 25,
      options: [
      ],
    },
    light_cav: {
      displayName: 'Light cavalry',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED, traits.ALLIES],
      cost: 16,
      options: [
      ],
    },
  },
  Spartacus: {
    ...charactersWithFamilies(),
    mob: {
      displayName: 'Armed mob',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: MIXED,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.OVERWHELM,
      ],
      cost: 7,
      options: [
      ],
    },
    freed: {
      displayName: 'Freed slaves with captured weapons',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SHIELD_OVERLAP,
        traits.WALL_OF_SPEARS,
      ],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    youngster: {
      displayName: 'Youngster',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    gladiators: {
      displayName: 'Gladiators',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: ADDITIONAL,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.CUTTHROAT,
        traits.PARRY,
        traits.GUARDED,
      ],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    gladiators_cap: {
      displayName: 'Gladiators with captured equipment',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SHIELD_OVERLAP,
        traits.WALL_OF_SPEARS,
        traits.CUTTHROAT,
      ],
      cost: 23,
      options: [
      ],
    },
    sheperds: {
      displayName: 'Shepherds',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 12,
      options: [
      ],
    },
    dogs: {
      displayName: 'Shepherds with dog packs',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.FERAL,
      ],
      cost: 10,
      options: [
      ],
    },
    cavalry: {
      displayName: 'Cavalry',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED, traits.IMPETUS],
      cost: 16,
      options: [
      ],
    },
  },
  'Later Selucid': {
    ...characters,
    charioteer,
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    militia: {
      displayName: 'City Militia',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: HEAVY_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.OFFENSIVE_SPEAR,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    pezhetairoi: {
      displayName: 'Pezhetairoi',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.MACEDONIAN,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.OFFENSIVE_SPEAR,
      ],
      cost: 17,
      options: [
      ],
    },
    argyraspides: {
      displayName: 'Argyraspides',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.MACEDONIAN,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.OFFENSIVE_SPEAR,
      ],
      cost: 21,
      options: [
      ],
    },
    thureophoroi: {
      displayName: 'Thureophoroi',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.EXTRA_JAVELIN, traits.WALL_OF_SPEARS, traits.OFFENSIVE_SPEAR],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    cataphracts: {
      displayName: 'Cataphracts',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: XYSTON,
      defaultBody: ENCLOSED,
      defaultBarding: BARDING,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.CHARGE,
        traits.DRILLED,
      ],
      cost: 25,
      options: [
      ],
    },
    hetairoi: {
      displayName: 'Hetairoi',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: XYSTON,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED,
        traits.DRILLED,
        traits.CHARGE,
      ],
      cost: 23,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    light_cav: {
      displayName: 'Greek Light cavalry',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED, traits.ALLIES],
      cost: 16,
      options: [
      ],
    },
    cretan: {
      displayName: 'Cretan archers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.AIM,
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },

    elephant: {
      dontCountForBreak: true,
      displayName: 'Asian Elephant',
      availability: RARE,
      fixedFigures: 5,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: '3+',
      traits: ['attacks(4)', 'wounds(5)', traits.ELEPHANT],
      cost: 14.4,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      dontCountForBreak: true,
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [traits.IRON_WILL],
      cost: 18,
      options: elephantOptions,
    },
  },
  'Later Macedonian or Helenistic Greek': {
    ...characters,
    charioteer,
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    peltasts: {
      displayName: 'Thracian peltasts',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.GUERRILLA,
        traits.VICIOUS,
        traits.ALLIES,
      ],
      cost: 15,
      options: [
      ],
    },
    militia: {
      displayName: 'City Militia',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: HEAVY_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.OFFENSIVE_SPEAR,
      ],
      cost: 17,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    pezhetairoi: {
      displayName: 'Pezhetairoi',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.MACEDONIAN,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.OFFENSIVE_SPEAR,
      ],
      cost: 17,
      options: [
      ],
    },
    thureophoroi: {
      displayName: 'Thureophoroi',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.EXTRA_JAVELIN, traits.WALL_OF_SPEARS, traits.OFFENSIVE_SPEAR],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 8,
      options: [
      ],
    },
    agema: {
      displayName: 'Agema',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.OFFENSIVE_SPEAR,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.MACEDONIAN,
      ],
      cost: 21,
      options: [
      ],
    },
    agema_thureophoroi: {
      displayName: 'Agema armed as Thureophoroi',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.EXTRA_JAVELIN,
        traits.WALL_OF_SPEARS,
        traits.OFFENSIVE_SPEAR,
        traits.DRILLED,
      ],
      cost: 24,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    greek_cav: {
      displayName: 'Greek/Thessalian Cavalry',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED,
        traits.EXTRA_JAVELIN,
        traits.IMPETUS,
      ],
      cost: 25,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    hetairoi: {
      displayName: 'Hetairoi',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: XYSTON,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED,
        traits.DRILLED,
        traits.CHARGE,
      ],
      cost: 22,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    light_cav: {
      displayName: 'Greek Light cavalry',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED, traits.ALLIES],
      cost: 16,
      options: [
      ],
    },
    cretan: {
      displayName: 'Cretan archers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.AIM,
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 17,
      options: [
      ],
    },
  },
  'Later Ptolemaic': {
    ...characters,
    charioteer,
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_UP_SHIELD,
      ],
    },
    levy_phalangites: {
      displayName: 'Levy Phalangites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.OFFENSIVE_SPEAR,
        traits.WALL_OF_SPEARS,
        traits.MACEDONIAN,
      ],
      cost: 14,
      options: [
      ],
    },
    phalangites: {
      displayName: 'Phalangites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.OFFENSIVE_SPEAR,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.MACEDONIAN,
      ],
      cost: 17,
      options: [
      ],
    },
    legionaries: {
      displayName: 'Allied Roman Legionaries',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.SHIELD_OVERLAP,
        traits.DRILLED,
        traits.IMPULSUM,
        traits.ALLIES,
      ],
      cost: 22,
      options: [
      ],
    },
    guard_phalangites: {
      displayName: 'Guard Phalangites',
      availability: CIVIS,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.OFFENSIVE_SPEAR,
        traits.WALL_OF_SPEARS,
        traits.DRILLED,
        traits.MACEDONIAN,
      ],
      cost: 21,
      options: [
      ],
    },
    thureophoroi: {
      displayName: 'Thureophoroi',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.EXTRA_JAVELIN, traits.WALL_OF_SPEARS, traits.OFFENSIVE_SPEAR],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    xystophoroi: {
      displayName: 'Xystophoroi',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: XYSTON,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.MOUNTED,
        traits.CHARGE,
        traits.DRILLED,
      ],
      cost: 22,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    light_cav: {
      displayName: 'Greek Light cavalry',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED, traits.ALLIES],
      cost: 16,
      options: [
      ],
    },
    cretan: {
      displayName: 'Cretan archers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.AIM,
        traits.SKIRMISH_SPECIALIST,
        traits.ALLIES,
      ],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
    elephant: {
      dontCountForBreak: true,
      displayName: 'African Forest Elephant',
      availability: RARE,
      fixedFigures: 4,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: '3+',
      traits: ['attacks(4)', 'wounds(4)', traits.ELEPHANT],
      cost: 16.5,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      dontCountForBreak: true,
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: RARE,
      traits: [traits.IRON_WILL],
      cost: 18,
      options: elephantOptions,
      defaultWeapon: JAVELIN,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
    },
  },
  Thracians: {
    ...characters,
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [],
      cost: 10,
      options: [
      ],
    },
    peltasts: {
      displayName: 'Peltasts',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.GUERRILLA,
        traits.VICIOUS,
      ],
      cost: 15,
      options: [
      ],
    },
    hoplites: {
      displayName: 'Mercenary Greek Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        traits.SHIELD_OVERLAP,
        traits.WALL_OF_SPEARS,
        traits.OFFENSIVE_SPEAR,
        traits.DRILLED,
        traits.ALLIES,
      ],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 8,
      options: [
      ],
    },
    vet_peltasts: {
      displayName: 'Veteran Peltasts',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.GUERRILLA,
        traits.VICIOUS,
      ],
      cost: 19,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    light_cav: {
      displayName: 'Light cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [traits.MOUNTED],
      cost: 16,
      options: [
      ],
    },
    vet_romphaia: {
      displayName: 'Veterans with Rhomphaia',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: AX,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.GUSHING],
      cost: 15,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
        OPT_UP_SHIELD_EXTRA,
      ],
    },
    horse: {
      displayName: 'Horse Archers',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [traits.MOUNTED],
      cost: 15,
      options: [
      ],
    },
    noble_cav: {
      displayName: 'Noble Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultBody: FULL,
      defaultShield: SHIELD,
      traits: [
        traits.MOUNTED,
        traits.EXTRA_JAVELIN,
        traits.IMPETUS,
      ],
      cost: 26,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
  },
};

export default eagles;
