import {
  samuraiCharacters,
  katanaCharacters,
  addTsukaiban,
  masterAss,
  sake,
  geisha,
  shrine,
} from './characters';

import {
  CIVIS,
  MILITES,
  RARE,
  NO_SHIELD,
  SHIELD,
  ENCLOSED,
  PARTIAL,
  PARTIAL_IMPROVED,
  FULL,
  ADDITIONAL,
  MIXED,
  CAVALRY_SPEAR_LONG,
  SWORD,
  BOW,
  GRENADES,
  REPEATING_XBOW,
  LIGHT_CANNON,
  HWACHA,
  THRUSTING,
  SLING,
  PIKE,
  ARQUEBUS,
  POLEARMS,
  HEAVY_WPN,
  WAR_BOW,
  OPT_MIXED,
  OPT_PAVAIS,
  OPT_PAVAIS_TATE,
  OPT_DOWN_ENCLOSED_TO_NO_ARMOUR,
  OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
  OPT_DOWN_PARTIAL_ARMOUR,
  OPT_DOWN_IMPROVED_PARTIAL_TO_NO_ARMOUR,
  OPT_UP_ENCLOSED_TO_IMP_ENCLOSED,
  OPT_UP_FULL_ARMOUR,
  OPT_ADDITIONAL_AND_PARRY,
  ENCLOSED_IMPROVED,
  OPT_DOWN_NO_ARMOUR,
  NO_ARMOUR,
  OPT_DOWN_FULL_TO_NO_ARMOUR,
  OPT_UP_PARTIAL_ARMOUR,
  OPT_POLE_FOR_WAR_BOW,
  OPT_UP_FULL_TO_ENCLOSED_ARMOUR,
  OPT_UPGRADE_POLEARM_MOMENTUM,
  OPT_EXTRA_WAR_BOW,
  XBOW,
  EARLY_FIREARMS,
} from './constants';

import traits from './traits';

const odaToyotomiTokugawa = {
  ...addTsukaiban(samuraiCharacters()),
  geisha,
  supportAshigaru: {
    displayName: 'Support Ashigaru',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 5,
    defaultWeapon: SWORD,
    defaultBody: PARTIAL,
    defaultShield: NO_SHIELD,
    traits: [
    ],
    cost: 9,
    options: [
      OPT_MIXED,
    ],
  },
  yariAshigaru: {
    displayName: 'Yari Ashigaru',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 5,
    defaultWeapon: THRUSTING,
    defaultBody: PARTIAL,
    defaultShield: NO_SHIELD,
    traits: [
      traits.HARINEZUMI,
      traits.OVERWHELM,
    ],
    cost: 12,
    options: [
    ],
  },
  nagaeAshigaru: {
    displayName: 'Nagae-Yari Ashigaru',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: PIKE,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      traits.HARINEZUMI,
      traits.UTEYA,
      traits.ASHIGARU,
      traits.EXTENDED_NAGAE,
    ],
    cost: 17,
    options: [
      OPT_DOWN_PARTIAL_ARMOUR,
    ],
  },
  proficientNagaeAshigaru: {
    displayName: 'Proficient Nagae-Yari Ashigaru',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 3,
    defaultWeapon: PIKE,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      traits.HARINEZUMI,
      traits.UTEYA,
      traits.ASHIGARU,
      traits.EXTENDED_NAGAE,
    ],
    cost: 19,
    options: [
      OPT_DOWN_PARTIAL_ARMOUR,
    ],
  },
  teppoAshigaru: {
    displayName: 'Teppo Ashigaru',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: ARQUEBUS,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      traits.ROTATIONAL_FIRE,
      traits.VOLLEY,
    ],
    cost: 17,
    options: [
      OPT_PAVAIS,
    ],
  },
  proficientTeppoAshigaru: {
    displayName: 'Proficient Teppo Ashigaru',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 3,
    defaultWeapon: ARQUEBUS,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      traits.ROTATIONAL_FIRE,
      traits.VOLLEY,
    ],
    cost: 19,
    options: [
      OPT_PAVAIS,
    ],
  },
  yumiAshigaru: {
    displayName: 'Yumi Ashigaru',
    availability: MILITES,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: WAR_BOW,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      traits.SKIRMISH_SPECIALIST,
      traits.OVERHEAD,
    ],
    cost: 17,
    options: [
      OPT_DOWN_PARTIAL_ARMOUR,
    ],
  },
  proficientYumiAshigaru: {
    displayName: 'Proficient Yumi Ashigaru',
    availability: MILITES,
    combat: 4,
    ranged: 5,
    grit: 3,
    defaultWeapon: WAR_BOW,
    defaultBody: FULL,
    defaultShield: NO_SHIELD,
    traits: [
      traits.SKIRMISH_SPECIALIST,
      traits.OVERHEAD,
      traits.AIM,
    ],
    cost: 20,
    options: [
    ],
  },
  naginataSamurai: {
    displayName: 'Naginata Samurai',
    availability: MILITES,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: POLEARMS,
    defaultBody: ENCLOSED,
    defaultShield: NO_SHIELD,
    traits: [
      traits.FUREKAESHI,
      traits.KURIDASHI,
      traits.HONOURABLE,
    ],
    cost: 23,
    options: [
    ],
  },
  yariSamurai: {
    displayName: 'Yari Samurai',
    availability: MILITES,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: THRUSTING,
    defaultBody: ENCLOSED,
    defaultShield: NO_SHIELD,
    traits: [
      traits.UTEYA,
      traits.HARINEZUMI,
      traits.HONOURABLE,
    ],
    cost: 22,
    options: [
    ],
  },
  yumiSamurai: {
    displayName: 'Yumi Samurai',
    availability: RARE,
    combat: 4,
    ranged: 4,
    grit: 3,
    defaultWeapon: WAR_BOW,
    defaultBody: ENCLOSED,
    defaultShield: NO_SHIELD,
    traits: [
      traits.HONOURABLE,
    ],
    cost: 22,
    options: [
    ],
  },
  mtdYariSamurai: {
    displayName: 'Mounted Yari Samurai',
    availability: RARE,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: CAVALRY_SPEAR_LONG,
    defaultBody: ENCLOSED,
    defaultShield: NO_SHIELD,
    traits: [
      traits.MOUNTED,
      traits.HONOURABLE,
      traits.FORM_UP,
      traits.CHARGE,
    ],
    cost: 26,
    options: [
    ],
  },
  mtdYumiSamurai: {
    displayName: 'Mounted Yumi Samurai',
    availability: RARE,
    combat: 4,
    ranged: 4,
    grit: 3,
    defaultWeapon: WAR_BOW,
    defaultBody: ENCLOSED,
    defaultShield: NO_SHIELD,
    traits: [
      traits.MOUNTED,
      traits.HONOURABLE,
    ],
    cost: 26,
    options: [
    ],
  },
  hatamotoSamurai: {
    displayName: 'Hatamoto Tetsubo Samurai',
    availability: RARE,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: HEAVY_WPN,
    defaultBody: ENCLOSED,
    defaultShield: NO_SHIELD,
    traits: [
      traits.HEAVY_STRIKE,
      traits.HONOURABLE,
      traits.DUTY,
      traits.IRON_WILL,
    ],
    cost: 24,
    options: [
    ],
  },
};
const katanas = {
  Shimazu: {
    ...addTsukaiban(samuraiCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
      ],
    },
    nagaeAshigaru: {
      displayName: 'Levy Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
      ],
      cost: 12,
      options: [
      ],
    },
    levyTeppoAshigaru: {
      displayName: 'Levy Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 12,
      options: [
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.VOLLEY,
      ],
      cost: 16,
      options: [
        OPT_PAVAIS,
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.AIM,
        traits.OVERHEAD,
      ],
      cost: 17,
      options: [
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.HONOURABLE,
      ],
      cost: 22,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    yumiSamurai: {
      displayName: 'Yumi Samurai',
      availability: MILITES,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.AIM,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    daishoSamurai: {
      displayName: 'Daisho Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: ADDITIONAL,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.RAIN,
        traits.PARRY_OFF,
        traits.HONOURABLE,
      ],
      cost: 21,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdYumiSamurai: {
      displayName: 'Mounted Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 26,
      options: [
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.FORM_UP,
        traits.CHARGE,
      ],
      cost: 26,
      options: [
      ],
    },
    hatamotoSamurai: {
      displayName: 'Hatamoto Daisho Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: ADDITIONAL,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.RAIN,
        traits.HONOURABLE,
        traits.PARRY_OFF,
        traits.DUTY,
        traits.IRON_WILL,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_NO_ARMOUR,
      ],
    },
    teppoSamurai: {
      displayName: 'Teppo Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
  },
  Otomo: {
    ...addTsukaiban(katanaCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
      ],
    },
    nagaeAshigaru: {
      displayName: 'Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HARINEZUMI,
        traits.UTEYA,
        traits.ASHIGARU,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    levyTeppoAshigaru: {
      displayName: 'Levy Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 13,
      options: [
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 17,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.FUROR,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    ronin: {
      displayName: 'Ronin',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.FICKLE,
      ],
      cost: 20,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.FUROR,
      ],
      cost: 22,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.FORM_UP,
        traits.CHARGE,
      ],
      cost: 25,
      options: [
      ],
    },
    teppoSamurai: {
      displayName: 'Mounted Teppo Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.MOUNTED_GUNNERY,
      ],
      cost: 26,
      options: [
      ],
    },
    yumiSamurai: {
      displayName: 'Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.AIM,
      ],
      cost: 22,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    european: {
      displayName: 'European Merceneries',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL_IMPROVED,
      improvedArmour: true,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
        traits.ROTATIONAL_FIRE,
      ],
      cost: 21,
      options: [
        OPT_DOWN_IMPROVED_PARTIAL_TO_NO_ARMOUR, // test trait
      ],
    },
    hatamotoSamurai: {
      displayName: 'Hatamoto Daisho Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: ADDITIONAL,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.RAIN,
        traits.BROTHERHOOD,
        traits.PARRY_OFF,
        traits.DUTY,
        traits.IRON_WILL,
      ],
      cost: 23,
      options: [
        OPT_UP_ENCLOSED_TO_IMP_ENCLOSED, // test trait
      ],
    },
  },
  Chosokabe: {
    ...addTsukaiban(samuraiCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
      ],
    },
    nagaeAshigaru: {
      displayName: 'Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HARINEZUMI,
        traits.UTEYA,
        traits.ASHIGARU,
      ],
      cost: 15,
      options: [
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 16,
      options: [
        OPT_PAVAIS,
      ],
    },
    proficientYumiAshigaru: {
      displayName: 'Proficient Yumi Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
        traits.AIM,
      ],
      cost: 19,
      options: [
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 15,
      options: [
        OPT_PAVAIS,
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.RUTHLESS,
        traits.HONOURABLE,
      ],
      cost: 22,
      options: [
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.HONOURABLE,
        traits.RUTHLESS,
      ],
      cost: 21,
      options: [
      ],
    },
    yumiSamurai: {
      displayName: 'Yumi Samurai',
      availability: MILITES,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.AIM,
        traits.HONOURABLE,
        traits.PARRY_RIPOSTE,
      ],
      cost: 22,
      options: [
        OPT_PAVAIS,
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.FORM_UP,
        traits.CHARGE,
      ],
      cost: 26,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdYumiSamurai: {
      displayName: 'Mounted Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 26,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    ronin: {
      displayName: 'Ronin',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.FICKLE,
      ],
      cost: 20,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdNaginataSamurai: {
      displayName: 'Mounted Naginata Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 25,
      options: [
      ],
    },
    mtdNaginataHatamoto: {
      displayName: 'Mounted Naginata Hatamoto',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.DUTY,
        traits.IRON_WILL,
      ],
      cost: 27,
      options: [
      ],
    },
  },
  Mori: {
    ...addTsukaiban(samuraiCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
      ],
    },
    nagaeAshigaru: {
      displayName: 'Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.ASHIGARU,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    levyTeppoAshigaru: {
      displayName: 'Levy Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 12,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    pirates: {
      displayName: 'Pirates',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: MIXED,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.GUERRILLA,
        traits.COMBINED_ARMS,
        traits.FICKLE,
        traits.RUTHLESS,
      ],
      cost: 12,
      options: [
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.HONOURABLE,
      ],
      cost: 22,
      options: [
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 17,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    naginataSohei: {
      displayName: 'Naginata Sohei Monks',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BROTHERHOOD,
        traits.ALLIES,
        traits.FUREKAESHI,
        traits.FUROR,
      ],
      cost: 21,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    teppoSamurai: {
      displayName: 'Teppo Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HONOURABLE,
      ],
      cost: 22,
      options: [
      ],
    },
    hatamotoSamurai: {
      displayName: 'Hatamoto Daisho Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: ADDITIONAL,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.RAIN,
        traits.HONOURABLE,
        traits.PARRY_OFF,
        traits.DUTY,
        traits.IRON_WILL,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_NO_ARMOUR,
      ],
    },
    fireBomb: {
      displayName: 'Fire Bomb Throwers',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: GRENADES,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 21,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.FORM_UP,
        traits.CHARGE,
      ],
      cost: 26,
      options: [
      ],
    },
  },
  Oda: odaToyotomiTokugawa,
  Toyotomi: odaToyotomiTokugawa,
  Tokugawa: odaToyotomiTokugawa,
  Takeda: {
    ...addTsukaiban(samuraiCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
      ],
    },
    nagaeAshigaru: {
      displayName: 'Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.ASHIGARU,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 17,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.FORM_UP,
        traits.CHARGE,
        traits.NORIKUZISHI,
      ],
      cost: 26,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.HONOURABLE,
      ],
      cost: 22,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    yumiSamurai: {
      displayName: 'Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.AIM,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdYumiSamurai: {
      displayName: 'Mounted Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 26,
      options: [
      ],
    },
    mtdNaginataSamurai: {
      displayName: 'Mounted Naginata Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 25,
      options: [
      ],
    },
    mtdHatamotoSamurai: {
      displayName: 'Mounted Hatamoto Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.DUTY,
        traits.IRON_WILL,
      ],
      cost: 27,
      options: [
      ],
    },
    mtdOnna: {
      displayName: 'Mounted Onna Bugeisha',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.DETERMINED,
      ],
      cost: 22,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    onna: {
      displayName: 'Onna Bugeisha',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.HONOURABLE,
        traits.DETERMINED,
      ],
      cost: 20,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
  },
  Uesugi: {
    ...addTsukaiban(samuraiCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    nagaeAshigaru: {
      displayName: 'Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.ASHIGARU,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    proficientNagaeAshigaru: {
      displayName: 'Proficient Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HARINEZUMI,
        traits.UTEYA,
        traits.ASHIGARU,
      ],
      cost: 18,
      options: [
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 16,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_PAVAIS,
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 17,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.HONOURABLE,
      ],
      cost: 22,
      options: [
      ],
    },
    naginataSohei: {
      displayName: 'Naginata Sohei Monks',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BROTHERHOOD,
        traits.FUREKAESHI,
        traits.FUROR,
      ],
      cost: 21,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    yumiSamurai: {
      displayName: 'Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.AIM,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.FORM_UP,
        traits.CHARGE,
      ],
      cost: 26,
      options: [
      ],
    },
    mtdYumiSamurai: {
      displayName: 'Mounted Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 26,
      options: [
      ],
    },
    tepppoMonks: {
      displayName: 'Teppo Monks',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BROTHERHOOD,
        traits.VOLLEY,
      ],
      cost: 21,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_PAVAIS,
      ],
    },
    mtdHatamotoSamurai: {
      displayName: 'Mounted Hatamoto Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.DUTY,
        traits.IRON_WILL,
      ],
      cost: 27,
      options: [
      ],
    },
  },
  Hojo: {
    ...addTsukaiban(samuraiCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    nagaeAshigaru: {
      displayName: 'Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.ASHIGARU,
      ],
      cost: 16,
      options: [
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 16,
      options: [
        OPT_PAVAIS_TATE,
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 14,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.KURIDASHI,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.HONOURABLE,
      ],
      cost: 22,
      options: [
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.FORM_UP,
        traits.CHARGE,
      ],
      cost: 26,
      options: [
      ],
    },
    ronin: {
      displayName: 'Ronin',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.FICKLE,
      ],
      cost: 20,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdYumiSamurai: {
      displayName: 'Mounted Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 26,
      options: [
      ],
    },
    mtdNaginataSamurai: {
      displayName: 'Mounted Naginata Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
      ],
      cost: 25,
      options: [
      ],
    },
    yumiSamurai: {
      displayName: 'Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.AIM,
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
      ],
    },
    hatamotoSamurai: {
      displayName: 'Hatamoto Daisho Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: ADDITIONAL,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.RAIN,
        traits.HONOURABLE,
        traits.PARRY_OFF,
        traits.DUTY,
        traits.IRON_WILL,
      ],
      cost: 23,
      options: [
        OPT_UP_ENCLOSED_TO_IMP_ENCLOSED,
        OPT_DOWN_ENCLOSED_TO_NO_ARMOUR,
      ],
    },
  },
  Date: {
    ...addTsukaiban(samuraiCharacters()),
    geisha,
    supportAshigaru: {
      displayName: 'Support Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 9,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_MIXED,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    nagaeAshigaru: {
      displayName: 'Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.ASHIGARU,
      ],
      cost: 16,
      options: [
      ],
    },
    proficientNagaeAshigaru: {
      displayName: 'Proficient Nagae-Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: PIKE,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HARINEZUMI,
        traits.UTEYA,
        traits.ASHIGARU,
      ],
      cost: 18,
      options: [
      ],
    },
    teppoAshigaru: {
      displayName: 'Teppo Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 16,
      options: [
      ],
    },
    yumiAshigaru: {
      displayName: 'Yumi Ashigaru',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 15,
      options: [
      ],
    },
    naginataSamurai: {
      displayName: 'Naginata Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED_IMPROVED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUREKAESHI,
        traits.FUROR,
        traits.HONOURABLE,
      ],
      cost: 24,
      options: [
      ],
    },
    ronin: {
      displayName: 'Ronin',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.FICKLE,
      ],
      cost: 20,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    yariSamurai: {
      displayName: 'Yari Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED_IMPROVED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
        traits.HONOURABLE,
      ],
      cost: 24,
      options: [
      ],
    },
    nodachiSamurai: {
      displayName: 'Nodachi Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_WPN,
      defaultBody: ENCLOSED_IMPROVED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.GUSHING,
        traits.FUROR,
        traits.HONOURABLE,
      ],
      cost: 24,
      options: [
      ],
    },
    yumiSamurai: {
      displayName: 'Yumi Samurai',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED_IMPROVED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HONOURABLE,
      ],
      cost: 23,
      options: [
      ],
    },
    mtdYariSamurai: {
      displayName: 'Mounted Yari Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR_LONG,
      defaultBody: ENCLOSED_IMPROVED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.HONOURABLE,
        traits.FORM_UP,
        traits.CHARGE,
      ],
      cost: 27,
      options: [
      ],
    },
    hatamotoYariSamurai: {
      displayName: 'Hatamoto Yari Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultBody: ENCLOSED_IMPROVED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.HARINEZUMI,
        traits.HONOURABLE,
        traits.DUTY,
        traits.IRON_WILL,
        traits.UTEYA,
      ],
      cost: 25,
      options: [
      ],
    },
  },
  'Ikko Ikki': {
    ...katanaCharacters(),
    shrine,
    peasants: {
      displayName: 'Peasants',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: MIXED,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.OVERWHELM,
      ],
      cost: 7,
      options: [
      ],
    },
    followers: {
      displayName: 'Followers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 4,
      defaultWeapon: MIXED,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.OVERWHELM,
      ],
      cost: 12,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    followersYari: {
      displayName: 'Followers with Yari',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.FUROR,
      ],
      cost: 12,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    followersTeppo: {
      displayName: 'Followers with Teppo',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 13,
      options: [
        OPT_DOWN_NO_ARMOUR,
        OPT_PAVAIS,
      ],
    },
    tepppoMonks: {
      displayName: 'Teppo Monks',
      availability: MILITES,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: ARQUEBUS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BROTHERHOOD,
        traits.VOLLEY,
      ],
      cost: 21,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_PAVAIS,
      ],
    },
    naginataMonks: {
      displayName: 'Naginata Monks',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BROTHERHOOD,
        traits.FUROR,
        traits.FUREKAESHI,
      ],
      cost: 21,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    nuns: {
      displayName: 'Nuns',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SISTERHOOD,
        traits.FUROR,
        traits.FUREKAESHI,
        traits.DETERMINED,
      ],
      cost: 20,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    followersBow: {
      displayName: 'Followers with Bow',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 12,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    ronin: {
      displayName: 'Ronin',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.FICKLE,
      ],
      cost: 20,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdNaginataMonks: {
      displayName: 'Mounted Naginata Monks',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.BROTHERHOOD,
      ],
      cost: 23,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    mtdYumiMonks: {
      displayName: 'Mounted Yumi Monks',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.BROTHERHOOD,
      ],
      cost: 24,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    tetsuboMonks: {
      displayName: 'Tetsubo Monks',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: HEAVY_WPN,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUROR,
        traits.BROTHERHOOD,
        traits.HEAVY_STRIKE,
      ],
      cost: 21,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    yumiMonks: {
      displayName: 'Yumi Monks',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.AIM,
        traits.BROTHERHOOD,
      ],
      cost: 21,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    mountedNuns: {
      displayName: 'Mounted Nuns',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SISTERHOOD,
        traits.DETERMINED,
        traits.MOUNTED,
      ],
      cost: 22,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
  },
  Iga: {
    ...katanaCharacters(),
    masterAss,
    scouts: {
      displayName: 'Scouts & Spies',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: SWORD,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BUSHMASTER,
      ],
      cost: 10,
      options: [
        OPT_MIXED,
      ],
    },
    guerrillas: {
      displayName: 'Guerrillas',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.GUERRILLA,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    yariAshigaru: {
      displayName: 'Yari Ashigaru',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.UTEYA,
      ],
      cost: 14,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    guerrillasYumi: {
      displayName: 'Guerrillas with Yumi',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BUSHMASTER,
        traits.GUERRILLA,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    guerrillasSling: {
      displayName: 'Guerrillas with Sling',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: SLING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BUSHMASTER,
        traits.GUERRILLA,
      ],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    guerrillasTeppo: {
      displayName: 'Guerrillas with Teppo',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BUSHMASTER,
        traits.GUERRILLA,
      ],
      cost: 16,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    YumiJiSamurai: {
      displayName: 'Yumi Ji-Samurai',
      availability: MILITES,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BUSHMASTER,
        traits.GUERRILLA,
        traits.AIM,
      ],
      cost: 22,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    daishoJiSamurai: {
      displayName: 'Daisho Ji-Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: ADDITIONAL,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.PARRY_OFF,
        traits.RAIN,
        traits.GUERRILLA,
        traits.BUSHMASTER,
      ],
      cost: 20,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    mixedJiSamurai: {
      displayName: 'Mixed Weapons Ji-Samurai',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.GUERRILLA,
        traits.BUSHMASTER,
      ],
      cost: 20,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    ronin: {
      displayName: 'Ronin',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.FICKLE,
      ],
      cost: 20,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mtdNaginataSamurai: {
      displayName: 'Mounted Naginata Samurai',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
      ],
      cost: 22,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    bandits: {
      displayName: 'Bandits',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: MIXED,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.GUERRILLA,
        traits.FICKLE,
      ],
      cost: 12,
      options: [
      ],
    },
  },
  Wako: {
    ...katanaCharacters(),
    sake,
    rabble: {
      displayName: 'Rabble',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: MIXED,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.ALLIES,
        traits.OVERWHELM,
      ],
      cost: 7,
      options: [
      ],
    },
    rabbleYari: {
      displayName: 'Rabble with Yari',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.WALL_OF_SPEARS,
        traits.ALLIES,
        traits.OVERWHELM,
      ],
      cost: 8,
      options: [
      ],
    },
    bandits: {
      displayName: 'Bandits',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: MIXED,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.GUERRILLA,
      ],
      cost: 11,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    banditsTeppo: {
      displayName: 'Teppo Bandits',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: ARQUEBUS,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BUSHMASTER,
        traits.RUTHLESS,
      ],
      cost: 12,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    marksmen: {
      displayName: 'Marksmen',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SHARPSHOOTER,
        traits.BUSHMASTER,
        traits.RUTHLESS,
      ],
      cost: 15,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    banditsArchers: {
      displayName: 'Bandit Archers',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.BUSHMASTER,
        traits.RUTHLESS,
        traits.AIM,
      ],
      cost: 14,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    veteranBandits: {
      displayName: 'Veteran Bandits',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: MIXED,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
        traits.GUERRILLA,
      ],
      cost: 17,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    veteranBanditsPolearms: {
      displayName: 'Veteran Bandits with Polearms',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: POLEARMS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.KURIDASHI,
        traits.RUTHLESS,
        traits.GUERRILLA,
      ],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    ronin: {
      displayName: 'Ronin',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.RUTHLESS,
      ],
      cost: 21,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    mountedRonin: {
      displayName: 'Mounted Ronin',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
      ],
      cost: 24,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    yumiRonin: {
      displayName: 'Yumi Ronin',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: ENCLOSED,
      defaultShield: NO_SHIELD,
      traits: [
        traits.RUTHLESS,
        traits.AIM,
      ],
      cost: 23,
      options: [
        OPT_DOWN_ENCLOSED_TO_FULL_ARMOUR,
      ],
    },
    fireBomb: {
      displayName: 'Fire Bomb Throwers',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: GRENADES,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 19,
      options: [
      ],
    },
    canon: {
      displayName: 'Light Cannon & two crew',
      fixedFigures: 2,
      countsDouble: true,
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_CANNON,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.IRON_WILL,
        traits.INDEPENDENT,
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 45,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    canon3: {
      displayName: 'Light Cannon & three crew',
      fixedFigures: 3,
      countsDouble: true,
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_CANNON,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.IRON_WILL,
        traits.INDEPENDENT,
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 34.3,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
  },
  'Joseon Koreans': {
    ...katanaCharacters(),
    guerrillas: {
      displayName: 'Guerrillas',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: MIXED,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.OVERWHELM,
      ],
      cost: 7,
      options: [
      ],
    },
    mob: {
      displayName: 'Righteous Mob',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 4,
      defaultWeapon: MIXED,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.OVERWHELM,
        traits.FUROR,
      ],
      cost: 10,
      options: [
      ],
    },
    militiaGlaives: {
      displayName: 'Militia with Glaives',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: POLEARMS,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.KURIDASHI,
      ],
      cost: 10,
      options: [
      ],
    },
    militiaFire: {
      displayName: 'Militia with fire lance',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: EARLY_FIREARMS,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 10,
      options: [
      ],
    },
    militiaArchers: {
      displayName: 'Militia archers',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: WAR_BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 12,
      options: [
      ],
    },
    infGlaives: {
      displayName: 'Infantry with Glaives',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: POLEARMS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.KURIDASHI,
        traits.WALL_OF_SPEARS,
      ],
      cost: 15,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    swordsmen: {
      displayName: 'Swordsmen',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.PARRY_OFF,
        traits.SHIELDS_UP,
      ],
      cost: 16,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_ADDITIONAL_AND_PARRY,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.OVERHEAD,
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 16,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    arquebusiers: {
      displayName: 'Arquebusiers',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 15,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    monks: {
      displayName: 'Monks',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.FUROR,
        traits.FUREKAESHI,
        traits.BROTHERHOOD,
      ],
      cost: 18,
      options: [
        OPT_EXTRA_WAR_BOW,
      ],
    },
    nomadCav: {
      displayName: 'Nomad/Militia Cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
      ],
      cost: 16,
      options: [
      ],
    },
    guardCav: {
      displayName: 'Guard Cavalry',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
      ],
      cost: 22,
      options: [
        OPT_UPGRADE_POLEARM_MOMENTUM,
        OPT_UP_FULL_ARMOUR,
      ],
    },
    guard: {
      displayName: 'Dismounted Guard',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 18,
      options: [
        OPT_UPGRADE_POLEARM_MOMENTUM,
        OPT_UP_FULL_ARMOUR,
      ],
    },
    hwacha: {
      displayName: 'Hwacha and 2 crew',
      fixedFigures: 2,
      countsDouble: true,
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: HWACHA,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.IRON_WILL,
        traits.INDEPENDENT,
      ],
      cost: 39,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    hwacha3: {
      displayName: 'Hwacha and 3 crew',
      fixedFigures: 3,
      countsDouble: true,
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: HWACHA,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.IRON_WILL,
        traits.INDEPENDENT,
      ],
      cost: 29.3,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
  },
  'Ming Chinese': {
    ...katanaCharacters(),
    spearmen: {
      displayName: 'Spearmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.UTEYA,
        traits.HARINEZUMI,
      ],
      cost: 14,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    infFire: {
      displayName: 'Firelance Infantry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: EARLY_FIREARMS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 13,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_PAVAIS_TATE,
      ],
    },
    crossbowmen: {
      displayName: 'Crossbowmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: XBOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
      ],
      cost: 14,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_PAVAIS_TATE,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
        traits.OVERHEAD,
      ],
      cost: 16,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    zhuge: {
      displayName: 'Zhuge Nu Infantry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: REPEATING_XBOW,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 15,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    swordsmen: {
      displayName: 'Swordsmen',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 4,
      defaultWeapon: SWORD,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.PARRY_OFF,
        traits.SHIELDS_UP,
      ],
      cost: 16,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    arquebusiers: {
      displayName: 'Arquebusiers',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: ARQUEBUS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.VOLLEY,
      ],
      cost: 14,
      options: [
        OPT_UP_FULL_ARMOUR,
        OPT_PAVAIS_TATE,
      ],
    },
    duckMelee: {
      displayName: 'Mandarin Duck Melee Infantry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: MIXED,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [
        traits.COMBINED_ARMS,
        traits.SHIELDS_UP,
        traits.MANDARIN,
      ],
      cost: 18,
      options: [
      ],
    },
    duckMissle: {
      displayName: 'Mandarin Duck Missle Infantry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: EARLY_FIREARMS,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MANDARIN,
      ],
      cost: 16,
      options: [
      ],
    },
    mercCavalry: {
      displayName: 'Mercenary Cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: WAR_BOW,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.ALLIES,
      ],
      cost: 16,
      options: [
      ],
    },
    mingCavalry: {
      displayName: 'Ming Cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
      ],
      cost: 20,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_POLE_FOR_WAR_BOW,
      ],
    },
    mtdFire: {
      displayName: 'Ming Mounted Firelance',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: EARLY_FIREARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
        traits.MOUNTED_GUNNERY,
      ],
      cost: 21,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    guardCav: {
      displayName: 'Guard Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: POLEARMS,
      defaultBody: FULL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.MOUNTED,
      ],
      cost: 22,
      options: [
        OPT_UP_FULL_TO_ENCLOSED_ARMOUR,
      ],
    },
    tiger: {
      displayName: 'Crouching Tiger Cannon & two crew',
      fixedFigures: 2,
      countsDouble: true,
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_CANNON,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.IRON_WILL,
        traits.INDEPENDENT,
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 45,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    tiger3: {
      displayName: 'Crouching Tiger Cannon & three crew',
      fixedFigures: 3,
      countsDouble: true,
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: LIGHT_CANNON,
      defaultBody: PARTIAL,
      defaultShield: NO_SHIELD,
      traits: [
        traits.IRON_WILL,
        traits.INDEPENDENT,
        traits.SKIRMISH_SPECIALIST,
      ],
      cost: 34.3,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
  },
};

export default katanas;
