/* eslint-disable no-undef */
import {
  HIDE_OPTION,
  NO_SHIELD,
  NO_ARMOUR,
  FULL,
  PARTIAL,
  SHIELD,
  HEAVY_SHIELD,
  THROWING,
  THRUSTING,
  CAVALRY_SPEAR,
  JAVELIN,
  CAVALRY_JAVELIN,
  SLING,
  BOW,
  SWORD,
  AX,
  PIKE,
  XYSTON,
  JAVELIN_THRUSTING,
  OPT_BUCKLER,
  OPT_SHIELD,
  OPT_DOWN_NO_ARMOUR,
  OPT_DOWN_PARTIAL_ARMOUR,
  OPT_UP_PARTIAL_ARMOUR,
  OPT_UP_FULL_ARMOUR,
  OPT_UPGRADE_CAVALRY_JAVELIN,
  OPT_DOWN_HEAVY_SHIELD,
  OPT_DOWN_BUCKLER,
  OPT_UP_HEAVY_SHIELD,
  OPT_DOWN_FULL_TO_NO_ARMOUR,
  OPT_CHARGING,
  OPT_UP_CHARIOT,
  characterOptions,
  elephantOptions,
} from './constants';

const characters = {
  lvl5: {
    isCharacter: true,
    fixedFigures: 1,
    displayName: 'Level V leader',
    availability: 'leader',
    cost: 155,
    options: characterOptions,
    defaultWeapon: SWORD,
    combat: 3,
    ranged: 5,
    grit: 3,
    commandRange: 10,
    commandPoints: 5,
    defaultShield: SHIELD,
    defaultBody: FULL,
    traits: ['attacks(3)', 'wounds(3)', 'Iron Will'],
  },
  lvl4: {
    isCharacter: true,
    fixedFigures: 1,
    displayName: 'Level IV leader',
    availability: 'leader',
    cost: 125,
    options: characterOptions,
    defaultWeapon: SWORD,
    combat: 3,
    ranged: 5,
    grit: 3,
    commandRange: 10,
    commandPoints: 4,
    defaultShield: SHIELD,
    defaultBody: FULL,
    traits: ['attacks(2)', 'wounds(3)', 'Iron Will'],
  },
  lvl3: {
    isCharacter: true,
    fixedFigures: 1,
    displayName: 'Level III leader',
    availability: 'leader',
    cost: 95,
    options: characterOptions,
    defaultWeapon: SWORD,
    combat: 3,
    ranged: 5,
    grit: 3,
    commandRange: 8,
    commandPoints: 3,
    defaultShield: SHIELD,
    defaultBody: FULL,
    traits: ['attacks(2)', 'wounds(2)', 'Iron Will'],
  },
  lvl2: {
    isCharacter: true,
    fixedFigures: 1,
    displayName: 'Level II leader',
    availability: 'leader',
    cost: 65,
    options: characterOptions,
    defaultWeapon: SWORD,
    combat: 3,
    ranged: 5,
    grit: 3,
    commandRange: 8,
    commandPoints: 2,
    defaultShield: SHIELD,
    defaultBody: FULL,
    traits: ['wounds(2)', 'Iron Will'],
  },
  soothsayer: {
    isCharacter: true,
    fixedFigures: 0,
    displayName: 'Soothsayer',
    availability: 'leader',
    cost: 15,
    options: [],
    combat: 0,
    ranged: 0,
    grit: 0,
    commandRange: 0,
    commandPoints: 0,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['luck'],
  },
};

function charactersWithChariots() {
  const ret = JSON.parse(JSON.stringify(characters));
  ret.lvl5.options = [...ret.lvl5.options, OPT_UP_CHARIOT];
  ret.lvl4.options = [...ret.lvl4.options, OPT_UP_CHARIOT];
  ret.lvl3.options = [...ret.lvl3.options, OPT_UP_CHARIOT];
  ret.lvl2.options = [...ret.lvl2.options, OPT_UP_CHARIOT];
  return ret;
}
const greeks = {
  ...characters,
  psiloi: {
    displayName: 'Psiloi',
    availability: 'civis',
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: JAVELIN,
    defaultBody: NO_ARMOUR,
    defaultShield: NO_SHIELD,
    traits: ['skirmish specialist'],
    cost: 8,
    options: [
    ],
  },
  archers: {
    displayName: 'Archers',
    availability: 'civis',
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: BOW,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['skirmish specialist'],
    cost: 8,
    options: [
      OPT_BUCKLER,
    ],
  },
  slingers: {
    displayName: 'Slingers',
    availability: 'civis',
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: SLING,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['skirmish specialist'],
    cost: 8,
    options: [
      OPT_BUCKLER,
    ],
  },
  peltasts: {
    displayName: 'Peltasts',
    availability: 'civis',
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['skirmish specialist'],
    cost: 13,
    options: [
    ],
  },
  raw: {
    displayName: 'Raw Citizen Hoplites',
    availability: 'civis',
    combat: 4,
    ranged: 5,
    grit: 5,
    defaultWeapon: THRUSTING,
    defaultShield: HEAVY_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['shield overlap', 'wall of spears', 'offensive spear'],
    cost: 13,
    options: [
      OPT_UP_PARTIAL_ARMOUR,
    ],
  },
  citizen: {
    displayName: 'Citizen Hoplites',
    availability: 'civis',
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: THRUSTING,
    defaultShield: HEAVY_SHIELD,
    defaultBody: PARTIAL,
    traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
    cost: 18,
    options: [
      OPT_DOWN_NO_ARMOUR,
    ],
  },
  thureophoroi: {
    displayName: 'Thureophoroi',
    availability: 'milites',
    combat: 3,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN_THRUSTING,
    defaultShield: SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
    cost: 16,
    options: [
    ],
  },
  veteran: {
    displayName: 'Veteran Hoplites',
    availability: 'milites',
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: THRUSTING,
    defaultShield: HEAVY_SHIELD,
    defaultBody: PARTIAL,
    traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
    cost: 22,
    options: [
      OPT_DOWN_NO_ARMOUR,
    ],
  },
  cretan: {
    displayName: 'Cretan Archers',
    availability: 'rare',
    combat: 4,
    ranged: 4,
    grit: 3,
    defaultWeapon: BOW,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: ['skirmish specialist', 'aimed shot', 'allies'],
    cost: 17,
    options: [
      OPT_BUCKLER,
    ],
  },
  cavalry: {
    displayName: 'Cavalry',
    availability: 'rare',
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: FULL,
    traits: ['mounted'],
    cost: 23,
    options: [
      OPT_DOWN_PARTIAL_ARMOUR,
      OPT_CHARGING,
    ],
  },

};

const lists = {
  Carthaginian: { // as book
    ...characters,
    javelinmen: {
      displayName: 'Javelin men',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    citizen: {
      displayName: 'Punic Citizens Levy',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears', 'offensive spear'],
      cost: 13,
      options: [
        OPT_DOWN_HEAVY_SHIELD,
      ],
    },
    infantry: {
      displayName: 'Punic Infantry',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
      cost: 18,
      options: [
      ],
    },
    scutarii: {
      displayName: 'Iberian Scutarii',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears', 'guerrilla ', 'impulsum', 'determined', 'allies'],
      cost: 18,
      options: [
      ],
    },
    veteran: {
      displayName: 'Veteran Punic Infantry',
      availability: 'milites',
      cost: 23,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    romanised: {
      displayName: 'Romanized Veteran Infantry',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: ['shield overlap', 'wall of spears', 'drilled'],
      cost: 24,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    numidian: {
      displayName: 'Numidian light cavalry',
      availability: 'milites',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['mounted', 'marauders'],
      cost: 17,
      options: [
      ],
    },
    iberianCav: {
      displayName: 'Iberian noble cavalry',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_JAVELIN,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: ['mounted', 'impetus', 'allies', 'extra equipment-(javelin)'],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    balearic: {
      displayName: 'Balearic slingers',
      availability: 'rare',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist', 'sling specialist', 'allies'],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
    punicCav: {
      displayName: 'Punic cavalry',
      availability: 'rare',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_JAVELIN,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: ['mounted', 'impetus', 'extra equipment-(javelin)'],
      cost: 26,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    elephant: {
      displayName: 'African Forest Elephant',
      availability: 'rare',
      fixedFigures: 4,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: 4,
      traits: ['attacks(3)', 'wounds(4)', 'elephant'],
      cost: 16.5,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: 'rare',
      traits: ['iron will'],
      cost: 18,
      options: elephantOptions,
      defaultWeapon: JAVELIN,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
    },
  },
  'Lowland Gallic': { // as book
    ...charactersWithChariots(),
    juves: {
      displayName: 'Juves',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears'],
      cost: 13,
      options: [
      ],
    },
    warriors: {
      displayName: 'warriors',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears', 'shield overlap', 'furor'],
      cost: 17,
      options: [
      ],
    },
    ligurians: {
      displayName: 'Ligurian Allies',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['guerrila', 'wall of spears', 'furor', 'allies'],
      cost: 17,
      options: [
      ],
    },
    nobles: {
      displayName: 'Nobles',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['wall of spears', 'shield overlap', 'furor'],
      cost: 23,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    mounted: {
      displayName: 'Mounted Nobles',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_JAVELIN,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: ['mounted', 'impetus', 'extra equipment-(javelin)'],
      cost: 26,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    gaesatae: {
      displayName: 'Gaesatae',
      availability: 'rare',
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['shield overlap', 'wall of spears', 'furor', 'Ira'],
      cost: 20,
      options: [
      ],
    },
  },
  Ligurian: { // as book
    ...charactersWithChariots(),
    juves: {
      displayName: 'Juves',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears'],
      cost: 12,
      options: [
        OPT_UP_HEAVY_SHIELD,
      ],
    },
    warriors: {
      displayName: 'warriors',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears', 'guerrilla', 'furor'],
      cost: 17,
      options: [
      ],
    },
    lowland: {
      displayName: 'Lowland Gallic Allies',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      traits: ['wall of spears,', 'shield overlap', 'furor', 'allies'],
      cost: 17,
      options: [
      ],
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
    },
    nobles: {
      displayName: 'Nobles',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['wall of spears', 'guerrilla', 'furor'],
      cost: 23,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    mounted: {
      displayName: 'Mounted Nobles',
      availability: 'rare',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_JAVELIN,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: ['mounted', 'impetus', 'extra equipment-(javelin)'],
      cost: 26,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    gaesatae: {
      displayName: 'Gaesatae',
      availability: 'rare',
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['shield overlap', 'wall of spears', 'furor', 'Ira'],
      cost: 20,
      options: [
      ],
    },
    dogs: {
      displayName: 'War Hounds',
      availability: 'rare',
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: '',
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['feral'],
      cost: 10,
      options: [
      ],
    },
  },
  'Greeks in Sicily': { // as book
    ...greeks,
    tyrant: {
      displayName: 'Tyrant Bodyguard',
      availability: 'rare',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled', 'fidelis'],
      cost: 24,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
  },
  'Greeks in Italy': { // as book
    ...greeks,
    tarantine: {
      displayName: 'Tarantine Nobles',
      availability: 'rare',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['mounted', 'marauders'],
      cost: 21,
      options: [
      ],
    },
  },
  'Celt-Iberian': { // as book
    ...characters,
    caetrati: {
      displayName: 'Caetrati',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: ['skirmish specialist', 'determined'],
      cost: 15,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears'],
      cost: 13,
      options: [
      ],
    },
    scutarii: {
      displayName: 'Celt-Iberian Scutarii',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears', 'shield overlap', 'impulsum', 'determined'],
      cost: 18,
      options: [
      ],
    },
    allied: {
      displayName: 'Allied Iberian Scutarii',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears', 'guerrilla', 'impulsum', 'determined', 'allies'],
      cost: 18,
      options: [
      ],
    },
    jinetes: {
      displayName: 'Jinetes',
      availability: 'milites',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: ['mounted'],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Celt-Iberian Veteran Scutarii',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultBody: PARTIAL,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears', 'shield overlap', 'impulsum', 'determined'],
      cost: 24,
      options: [
      ],
    },
    nobles: {
      displayName: 'Celt-Iberian Nobles',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_JAVELIN,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: ['mounted', 'impetus', 'extra equipment- (javelin)'],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Celt-Iberian Slingers',
      availability: 'milites',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    balearic: {
      displayName: 'Balearic Slingers',
      availability: 'rare',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist', 'sling specialist', 'allies'],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  Iberian: { // as book
    ...characters,
    caetrati: {
      displayName: 'Caetrati',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: ['skirmish specialist', 'determined'],
      cost: 15,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears'],
      cost: 13,
      options: [
      ],
    },
    scutarii: {
      displayName: 'Iberian Scutarii',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears', 'guerrilla', 'impulsum', 'determined'],
      cost: 18,
      options: [
      ],
    },
    allied: {
      displayName: 'Allied Celt-Iberian Scutarii',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears', 'shield overlap', 'impulsum', 'determined', 'allies'],
      cost: 18,
      options: [
      ],
    },
    jinetes: {
      displayName: 'Jinetes',
      availability: 'milites',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: ['mounted'],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Celt-Iberian Veteran Scutarii',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultBody: PARTIAL,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears', 'guerrilla', 'impulsum', 'determined'],
      cost: 24,
      options: [
      ],
    },
    nobles: {
      displayName: 'Mounted Iberian Nobles',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_JAVELIN,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: ['mounted', 'impetus', 'extra equipment- (javelin)'],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Iberian Slingers',
      availability: 'milites',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    balearic: {
      displayName: 'Balearic Slingers',
      availability: 'rare',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist', 'sling specialist', 'allies'],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  Lusitanian: { // as book
    ...characters,
    caetrati: {
      displayName: 'Caetrati',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: ['skirmish specialist', 'determined'],
      cost: 15,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears'],
      cost: 13,
      options: [
      ],
    },
    warriors: {
      displayName: 'Lusitanian Warriors',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: ['wall of spears', 'guerrilla', 'impulsum', 'determined'],
      cost: 17,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    allied: {
      displayName: 'Allied Celt-Iberian Scutarii',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: ['wall of spears', 'shield overlap', 'impulsum', 'determined', 'allies'],
      cost: 18,
      options: [
      ],
    },
    jinetes: {
      displayName: 'Jinetes',
      availability: 'milites',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: ['mounted'],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Lusitanian Veteran Scutarii',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: ['wall of spears', 'guerrilla', 'impulsum', 'determined'],
      cost: 24,
      options: [
      ],
    },
    nobles: {
      displayName: 'Mounted Iberian Nobles',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_JAVELIN,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: ['mounted', 'impetus', 'extra equipment- (javelin)'],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Lusitanian Slingers',
      availability: 'milites',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    balearic: {
      displayName: 'Balearic Slingers',
      availability: 'rare',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist', 'sling specialist', 'allies'],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  'Etruscan or Campanian': { // as book
    ...charactersWithChariots(),
    javelinmen: {
      displayName: 'Javelin men',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    samnite: {
      displayName: 'Samnite Allies',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'guerrilla', 'allies'],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    '3rd': {
      displayName: '3rd Class Citizens',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['shield overlap', 'wall of spears', 'offensive spear'],
      cost: 13,
      options: [
      ],
    },
    '2nd': {
      displayName: '2nd Class Citizens',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    '1st': {
      displayName: '1st Class Citizens',
      availability: 'civis',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
      cost: 18,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: 'milites',
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
      defaultWeapon: SLING,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
    },
    cavalry: {
      displayName: 'Noble Cavalry',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: ['mounted', 'impetus'],
      cost: 23,
      options: [
        OPT_UPGRADE_CAVALRY_JAVELIN,
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    axmen: {
      displayName: 'Axmen',
      availability: 'rare',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: AX,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: ['skirmish specialist'],
      cost: 14,
      options: [

      ],
    },
  },
  Samnite: { // as book
    ...characters,
    javelinmen: {
      displayName: 'Javelin men',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    hoplites: {
      displayName: 'Campanian Allied Hoplites',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'allies'],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [''],
      cost: 12,
      options: [
      ],
    },
    samnite: {
      displayName: 'Samnite Warriors',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'guerrilla'],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    veterans: {
      displayName: 'Veteran Samnite Warriors',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'guerrilla'],
      cost: 23,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: 'milites',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    cavalry: {
      displayName: 'Samnite Cavalry',
      availability: 'rare',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: ['mounted'],
      cost: 23,
      options: [
        OPT_CHARGING,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
  },
  Roman: {
    ...characters,
    leves: {
      displayName: 'Leves',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
      ],
    },
    velites: {
      displayName: 'Velites',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 13,
      options: [
      ],
    },
    raw: {
      displayName: 'Raw Legionnaries',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['shield overlap', 'wall of spears'],
      cost: 14,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    samnite: {
      displayName: 'Samnite Allies',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'guerrilla', 'allies'],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    hastati: {
      displayName: 'Hastati',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'impulsum', 'drilled'],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    principes: {
      displayName: 'Principes',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: ['shield overlap', 'wall of spears', 'impulsum', 'drilled'],
      cost: 25,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    tirarii: {
      displayName: 'tirarii',
      availability: 'rare',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'fidelis', 'drilled'],
      cost: 24,
      options: [],
    },
    extraordinarii: {
      displayName: 'Italian Extraordinarii',
      availability: 'rare',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'guerilla tactics', 'allies'],
      cost: 24,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    equites: {
      displayName: 'Equites or Alae',
      availability: 'rare',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: ['mounted', 'impetus'],
      cost: 23,
      options: [
        OPT_UPGRADE_CAVALRY_JAVELIN,
      ],
    },
    cretan: {
      displayName: 'Cretan Archers',
      availability: 'rare',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist', 'aimed shot', 'allies'],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  Numidian: {
    ...characters,
    javelinmen: {
      displayName: 'Javelin men',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears'],
      cost: 13,
      options: [
        OPT_DOWN_BUCKLER,
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['wall of spears', 'guerrilla', 'enfurance'],
      cost: 17,
      options: [
        OPT_DOWN_BUCKLER,
      ],
    },
    cavalry: {
      displayName: 'Numidian Cavalry',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['mounted', 'marauders'],
      cost: 17,
      options: [
      ],
    },
    nobles: {
      displayName: 'Numidian Nobles',
      availability: 'milites',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['mounted', 'marauders'],
      cost: 21,
      options: [
      ],
    },
    legionaires: {
      displayName: 'Immitation Legionaires',
      availability: 'rare',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'guerrilla', 'endurance'],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    elephant: {
      displayName: 'African Forest Elephant',
      availability: 'rare',
      fixedFigures: 4,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: 3,
      traits: ['attacks(3)', 'wounds(4)', 'elephant'],
      cost: 16.5,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: 'rare',
      traits: ['iron will'],
      cost: 18,
      options: elephantOptions,
      defaultWeapon: JAVELIN,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
    },
  },
  Phyrrus: {
    ...characters,
    psiloi: {
      displayName: 'Psiloi',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: 'civis',
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['skirmish specialist'],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    javelin: {
      displayName: 'Pezhetairoi with Javelin',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [],
      cost: 14,
      options: [
      ],
    },
    pikes: {
      displayName: 'Pezhetairoi with Pikes',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: ['wall of spears', 'offensive spear', 'macedonian drill', 'drilled'],
      cost: 17,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    allies: {
      displayName: 'Allied Raw Hoplites',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'allies'],
      cost: 18,
      options: [
      ],
    },
    hoplites: {
      displayName: 'Hoplites',
      availability: 'civis',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear'],
      cost: 18,
      options: [
      ],
    },
    veteran: {
      displayName: 'Citizen Hoplites',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: ['shield overlap', 'wall of spears', 'offensive spear', 'drilled'],
      cost: 22,
      options: [
      ],
    },
    cavalry: {
      displayName: 'Greek Style cavalry',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: ['mounted'],
      cost: 22,
      options: [
        OPT_CHARGING,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    hetairoi: {
      displayName: 'Hetairoi',
      availability: 'milites',
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: XYSTON,
      defaultShield: NO_SHIELD,
      defaultBody: FULL,
      traits: ['massed charge', 'drilled', 'mounted'],
      cost: 22,
      options: [
        OPT_CHARGING,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    mounted: {
      displayName: 'Mounted Skirmishers',
      availability: 'rare',
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: ['mounted'],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    elephant: {
      displayName: 'Asian Elephant',
      availability: 'rare',
      fixedFigures: 5,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: 3,
      traits: ['attacks(3)', 'wounds(5)', 'elephant'],
      cost: 14.4,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: 'rare',
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: ['iron will'],
      cost: 18,
      options: elephantOptions,
    },
  },
};

export default lists;
