/* eslint-disable no-undef */
import {
  MILITES,
  CIVIS,
  RARE,
  HIDE_OPTION,
  NO_SHIELD,
  NO_ARMOUR,
  FULL,
  PARTIAL,
  SHIELD,
  HEAVY_SHIELD,
  THROWING,
  THRUSTING,
  CAVALRY_SPEAR,
  JAVELIN,
  SLING,
  BOW,
  AX,
  PIKE,
  XYSTON,
  JAVELIN_THRUSTING,
  OPT_BUCKLER,
  OPT_SHIELD,
  OPT_DOWN_NO_ARMOUR,
  OPT_DOWN_PARTIAL_ARMOUR,
  OPT_UP_PARTIAL_ARMOUR,
  OPT_UP_FULL_ARMOUR,
  OPT_UPGRADE_CAVALRY_JAVELIN,
  OPT_DOWN_HEAVY_SHIELD,
  OPT_UP_HEAVY_SHIELD,
  OPT_DOWN_FULL_TO_NO_ARMOUR,
  OPT_CHARGING,
  elephantOptions,
} from './constants';

import {
  TRAIT_IRON_WILL,
  TRAIT_SHIELD_OVERLAP,
  TRAIT_SKIRMISH_SPECIALIST,
  TRAIT_WALL_OF_SPEARS,
  TRAIT_OFFENSIVE_SPEAR,
  TRAIT_DRILLED,
  TRAIT_GUERRILLA,
  TRAIT_FUROR,
  TRAIT_ALLIES,
  TRAIT_MOUNTED,
  TRAIT_IMPETUS,
  TRAIT_IRA,
  TRAIT_FIDELIS,
  TRAIT_FERAL,
  TRAIT_EXTRA_JAVELIN,
  TRAIT_DETERMINED,
  TRAIT_IMPULSUM,
  TRAIT_AIM,
  TRAIT_MACEDONIAN,
  TRAIT_ENDURANCE,
  TRAIT_MARAUDERS,
  TRAIT_ELEPHANT,
  TRAIT_CHARGE,
  TRAIT_SLING,
  TRAIT_DOUBLE,
} from './traits';

import {
  charactersWithAbilities,
  charactersWithChariots,
} from './characters';

const greeks = {
  ...charactersWithAbilities('greek'),
  psiloi: {
    displayName: 'Psiloi',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: JAVELIN,
    defaultBody: NO_ARMOUR,
    defaultShield: NO_SHIELD,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 8,
    options: [
    ],
  },
  archers: {
    displayName: 'Archers',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: BOW,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 8,
    options: [
      OPT_BUCKLER,
    ],
  },
  slingers: {
    displayName: 'Slingers',
    availability: CIVIS,
    combat: 5,
    ranged: 5,
    grit: 5,
    defaultWeapon: SLING,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 8,
    options: [
      OPT_BUCKLER,
    ],
  },
  peltasts: {
    displayName: 'Peltasts',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST],
    cost: 13,
    options: [
    ],
  },
  raw: {
    displayName: 'Raw Citizen Hoplites',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 5,
    defaultWeapon: THRUSTING,
    defaultShield: HEAVY_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
    cost: 13,
    options: [
      OPT_UP_PARTIAL_ARMOUR,
    ],
  },
  citizen: {
    displayName: 'Citizen Hoplites',
    availability: CIVIS,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: THRUSTING,
    defaultShield: HEAVY_SHIELD,
    defaultBody: PARTIAL,
    traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
    cost: 18,
    options: [
      OPT_DOWN_NO_ARMOUR,
    ],
  },
  thureophoroi: {
    displayName: 'Thureophoroi',
    availability: MILITES,
    combat: 4,
    ranged: 5,
    grit: 4,
    defaultWeapon: JAVELIN_THRUSTING,
    defaultShield: SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_EXTRA_JAVELIN, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
    cost: 16,
    options: [
    ],
  },
  veteran: {
    displayName: 'Veteran Hoplites',
    availability: MILITES,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: THRUSTING,
    defaultShield: HEAVY_SHIELD,
    defaultBody: PARTIAL,
    traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
    cost: 22,
    options: [
      OPT_DOWN_NO_ARMOUR,
    ],
  },
  cretan: {
    displayName: 'Cretan Archers',
    availability: RARE,
    combat: 4,
    ranged: 4,
    grit: 3,
    defaultWeapon: BOW,
    defaultShield: NO_SHIELD,
    defaultBody: NO_ARMOUR,
    traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_AIM, TRAIT_ALLIES],
    cost: 17,
    options: [
      OPT_BUCKLER,
    ],
  },
  cavalry: {
    displayName: 'Cavalry',
    availability: RARE,
    combat: 3,
    ranged: 5,
    grit: 3,
    defaultWeapon: JAVELIN,
    defaultShield: SHIELD,
    defaultBody: FULL,
    traits: [TRAIT_MOUNTED],
    cost: 23,
    options: [
      OPT_DOWN_PARTIAL_ARMOUR,
      OPT_CHARGING,
    ],
  },

};

const punic = {
  Carthaginian: { // as book
    ...charactersWithAbilities('punic'),
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    citizen: {
      displayName: 'Punic Citizens Levy',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
      cost: 13,
      options: [
        OPT_DOWN_HEAVY_SHIELD,
      ],
    },
    infantry: {
      displayName: 'Punic Infantry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      cost: 18,
      options: [
      ],
    },
    scutarii: {
      displayName: 'Iberian Scutarii',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS,
        TRAIT_GUERRILLA,
        TRAIT_IMPULSUM,
        TRAIT_DETERMINED,
        TRAIT_ALLIES],
      cost: 18,
      options: [
      ],
    },
    veteran: {
      displayName: 'Veteran Punic Infantry',
      availability: MILITES,
      cost: 23,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    romanised: {
      displayName: 'Romanized Veteran Infantry',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_DRILLED],
      cost: 24,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    numidian: {
      displayName: 'Numidian light cavalry',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS],
      cost: 17,
      options: [
      ],
    },
    iberianCav: {
      displayName: 'Iberian noble cavalry',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_ALLIES, TRAIT_EXTRA_JAVELIN],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    balearic: {
      displayName: 'Balearic slingers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_SLING, TRAIT_ALLIES],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
    punicCav: {
      displayName: 'Punic cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_EXTRA_JAVELIN],
      cost: 26,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    elephant: {
      dontCountForBreak: true,
      displayName: 'African Forest Elephant',
      availability: RARE,
      fixedFigures: 4,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: '3+',
      traits: ['attacks(4)', 'wounds(4)', TRAIT_ELEPHANT],
      cost: 16.5,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      dontCountForBreak: true,
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: RARE,
      traits: [TRAIT_IRON_WILL],
      cost: 18,
      options: elephantOptions,
      defaultWeapon: JAVELIN,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
    },
  },
  'Lowland Gallic': { // as book
    ...charactersWithChariots('gallic'),
    juves: {
      displayName: 'Juves',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS],
      cost: 13,
      options: [
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_SHIELD_OVERLAP, TRAIT_FUROR],
      cost: 17,
      options: [
      ],
    },
    ligurians: {
      displayName: 'Ligurian Allies',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_GUERRILLA, TRAIT_WALL_OF_SPEARS, TRAIT_FUROR, TRAIT_ALLIES],
      cost: 17,
      options: [
      ],
    },
    nobles: {
      displayName: 'Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_SHIELD_OVERLAP, TRAIT_FUROR],
      cost: 23,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    mounted: {
      displayName: 'Mounted Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_EXTRA_JAVELIN],
      cost: 26,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    gaesatae: {
      displayName: 'Gaesatae',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_FUROR, TRAIT_IRA],
      cost: 20,
      options: [
      ],
    },
  },
  Ligurian: { // as book
    ...charactersWithChariots('gallic'),
    juves: {
      displayName: 'Juves',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS],
      cost: 12,
      options: [
        OPT_UP_HEAVY_SHIELD,
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_FUROR],
      cost: 17,
      options: [
      ],
    },
    lowland: {
      displayName: 'Lowland Gallic Allies',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_SHIELD_OVERLAP, TRAIT_FUROR, TRAIT_ALLIES],
      cost: 17,
      options: [
      ],
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
    },
    nobles: {
      displayName: 'Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_FUROR],
      cost: 23,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    mounted: {
      displayName: 'Mounted Nobles',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_EXTRA_JAVELIN],
      cost: 26,
      options: [
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    gaesatae: {
      displayName: 'Gaesatae',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_FUROR, TRAIT_IRA],
      cost: 20,
      options: [
      ],
    },
    dogs: {
      displayName: 'War Hounds',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 3,
      defaultWeapon: '',
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_FERAL],
      cost: 10,
      options: [
      ],
    },
  },
  'Greeks in Sicily': { // as book
    ...greeks,
    tyrant: {
      displayName: 'Tyrant Bodyguard',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_SHIELD_OVERLAP,
        TRAIT_WALL_OF_SPEARS,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_DRILLED,
        TRAIT_FIDELIS],
      cost: 24,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
  },
  'Greeks in Italy': { // as book
    ...greeks,
    tarantine: {
      displayName: 'Tarantine Nobles',
      availability: MILITES,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS],
      cost: 21,
      options: [
      ],
    },
  },
  'Celt-Iberian': { // as book
    ...charactersWithAbilities('spanish'),
    caetrati: {
      displayName: 'Caetrati',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_DETERMINED],
      cost: 14,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS],
      cost: 13,
      options: [
      ],
    },
    scutarii: {
      displayName: 'Celt-Iberian Scutarii',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_SHIELD_OVERLAP, TRAIT_IMPULSUM, TRAIT_DETERMINED],
      cost: 18,
      options: [
      ],
    },
    allied: {
      displayName: 'Allied Iberian Scutarii',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS,
        TRAIT_GUERRILLA,
        TRAIT_IMPULSUM,
        TRAIT_DETERMINED,
        TRAIT_ALLIES],
      cost: 18,
      options: [
      ],
    },
    jinetes: {
      displayName: 'Jinetes',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Celt-Iberian Veteran Scutarii',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultBody: PARTIAL,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_SHIELD_OVERLAP, TRAIT_IMPULSUM, TRAIT_DETERMINED],
      cost: 24,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    nobles: {
      displayName: 'Celt-Iberian Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_EXTRA_JAVELIN],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Celt-Iberian Slingers',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    balearic: {
      displayName: 'Balearic Slingers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_SLING, TRAIT_ALLIES],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  Iberian: { // as book
    ...charactersWithAbilities('spanish'),
    caetrati: {
      displayName: 'Caetrati',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_DETERMINED],
      cost: 14,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS],
      cost: 13,
      options: [
      ],
    },
    scutarii: {
      displayName: 'Iberian Scutarii',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_IMPULSUM, TRAIT_DETERMINED],
      cost: 18,
      options: [
      ],
    },
    allied: {
      displayName: 'Allied Celt-Iberian Scutarii',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS,
        TRAIT_SHIELD_OVERLAP,
        TRAIT_IMPULSUM,
        TRAIT_DETERMINED,
        TRAIT_ALLIES],
      cost: 18,
      options: [
      ],
    },
    jinetes: {
      displayName: 'Jinetes',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Iberian Veteran Scutarii',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultBody: PARTIAL,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_IMPULSUM, TRAIT_DETERMINED],
      cost: 24,
      options: [
      ],
    },
    nobles: {
      displayName: 'Mounted Iberian Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_EXTRA_JAVELIN],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Iberian Slingers',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    balearic: {
      displayName: 'Balearic Slingers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_SLING, TRAIT_ALLIES],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  Lusitanian: { // as book
    ...charactersWithAbilities('spanish'),
    caetrati: {
      displayName: 'Caetrati',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_DETERMINED],
      cost: 14,
      options: [
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS],
      cost: 13,
      options: [
      ],
    },
    warriors: {
      displayName: 'Lusitanian Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_IMPULSUM, TRAIT_DETERMINED],
      cost: 17,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    allied: {
      displayName: 'Allied Celt-Iberian Scutarii',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultBody: NO_ARMOUR,
      defaultShield: HEAVY_SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS,
        TRAIT_SHIELD_OVERLAP,
        TRAIT_IMPULSUM,
        TRAIT_DETERMINED,
        TRAIT_ALLIES],
      cost: 18,
      options: [
      ],
    },
    jinetes: {
      displayName: 'Jinetes',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED],
      cost: 16,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    veteran: {
      displayName: 'Lusitanian Veteran Scutarii',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_IMPULSUM, TRAIT_DETERMINED],
      cost: 24,
      options: [
      ],
    },
    nobles: {
      displayName: 'Mounted Iberian Nobles',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultBody: PARTIAL,
      defaultShield: SHIELD,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS, TRAIT_EXTRA_JAVELIN],
      cost: 25,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Lusitanian Slingers',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    balearic: {
      displayName: 'Balearic Slingers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: SLING,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_SLING, TRAIT_ALLIES],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  'Etruscan or Campanian': { // as book
    ...charactersWithChariots('italian'),
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    samnite: {
      displayName: 'Samnite Allies',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_ALLIES],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    '3rd': {
      displayName: '3rd Class Citizens',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
      cost: 13,
      options: [
      ],
    },
    '2nd': {
      displayName: '2nd Class Citizens',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    '1st': {
      displayName: '1st Class Citizens',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      cost: 23,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: MILITES,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
      defaultWeapon: SLING,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
    },
    cavalry: {
      displayName: 'Noble Cavalry',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS],
      cost: 23,
      options: [
        OPT_UPGRADE_CAVALRY_JAVELIN,
        OPT_DOWN_PARTIAL_ARMOUR,
        OPT_DOWN_FULL_TO_NO_ARMOUR,
      ],
    },
    axmen: {
      displayName: 'Axmen',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: AX,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_DOUBLE],
      cost: 14,
      options: [

      ],
    },
  },
  Samnite: { // as book
    ...charactersWithAbilities('italian'),
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    hoplites: {
      displayName: 'Campanian Allied Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [
        TRAIT_DRILLED,
        TRAIT_SHIELD_OVERLAP,
        TRAIT_WALL_OF_SPEARS,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_ALLIES,
      ],
      cost: 18,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [''],
      cost: 12,
      options: [
      ],
    },
    samnite: {
      displayName: 'Samnite Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    veterans: {
      displayName: 'Veteran Samnite Warriors',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA],
      cost: 23,
      options: [
        OPT_UP_FULL_ARMOUR,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: MILITES,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    cavalry: {
      displayName: 'Samnite Cavalry',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_MOUNTED],
      cost: 23,
      options: [
        OPT_CHARGING,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
  },
  Roman: {
    ...charactersWithAbilities('roman'),
    leves: {
      displayName: 'Leves',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
      ],
    },
    velites: {
      displayName: 'Velites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 13,
      options: [
      ],
    },
    raw: {
      displayName: 'Raw Legionnaries',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS],
      cost: 14,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    samnite: {
      displayName: 'Samnite Allies',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_ALLIES],
      cost: 19,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    hastati: {
      displayName: 'Hastati',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_IMPULSUM, TRAIT_DRILLED],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    principes: {
      displayName: 'Principes',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_IMPULSUM, TRAIT_DRILLED],
      cost: 25,
      options: [
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    tirarii: {
      displayName: 'tirarii',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_SHIELD_OVERLAP,
        TRAIT_WALL_OF_SPEARS,
        TRAIT_OFFENSIVE_SPEAR,
        TRAIT_FIDELIS,
        TRAIT_DRILLED],
      cost: 24,
      options: [],
    },
    extraordinarii: {
      displayName: 'Italian Extraordinarii',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_ALLIES],
      cost: 24,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    equites: {
      displayName: 'Equites or Alae',
      availability: RARE,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: CAVALRY_SPEAR,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_MOUNTED, TRAIT_IMPETUS],
      cost: 23,
      options: [
        OPT_UPGRADE_CAVALRY_JAVELIN,
      ],
    },
    cretan: {
      displayName: 'Cretan Archers',
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST, TRAIT_AIM, TRAIT_ALLIES],
      cost: 17,
      options: [
        OPT_BUCKLER,
      ],
    },
  },
  Numidian: {
    ...charactersWithAbilities('numidian'),
    javelinmen: {
      displayName: 'Javelin men',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_SHIELD,
      ],
    },
    tribesmen: {
      displayName: 'Tribesmen',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS],
      cost: 13,
      options: [
        OPT_DOWN_HEAVY_SHIELD,
      ],
    },
    warriors: {
      displayName: 'Warriors',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_ENDURANCE],
      cost: 17,
      options: [
        OPT_DOWN_HEAVY_SHIELD,
      ],
    },
    cavalry: {
      displayName: 'Numidian Cavalry',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS],
      cost: 17,
      options: [
      ],
    },
    nobles: {
      displayName: 'Numidian Nobles',
      availability: MILITES,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED, TRAIT_MARAUDERS],
      cost: 21,
      options: [
      ],
    },
    legionaires: {
      displayName: 'Immitation Legionaires',
      availability: MILITES,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THROWING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_GUERRILLA, TRAIT_ENDURANCE],
      cost: 20,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    elephant: {
      dontCountForBreak: true,
      displayName: 'African Forest Elephant',
      availability: RARE,
      fixedFigures: 4,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: '3+',
      traits: ['attacks(4)', 'wounds(4)', TRAIT_ELEPHANT],
      cost: 16.5,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      dontCountForBreak: true,
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: RARE,
      traits: [TRAIT_IRON_WILL],
      cost: 18,
      options: elephantOptions,
      defaultWeapon: JAVELIN,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
    },
  },
  Phyrrus: {
    ...charactersWithAbilities('pyrric'),
    psiloi: {
      displayName: 'Psiloi',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: JAVELIN,
      defaultBody: NO_ARMOUR,
      defaultShield: NO_SHIELD,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    archers: {
      displayName: 'Archers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: BOW,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    slingers: {
      displayName: 'Slingers',
      availability: CIVIS,
      combat: 5,
      ranged: 5,
      grit: 5,
      defaultWeapon: SLING,
      defaultShield: NO_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SKIRMISH_SPECIALIST],
      cost: 8,
      options: [
        OPT_BUCKLER,
      ],
    },
    javelin: {
      displayName: 'Pezhetairoi with Javelin',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [],
      cost: 14,
      options: [
      ],
    },
    pikes: {
      displayName: 'Pezhetairoi with Pikes',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: PIKE,
      defaultShield: SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_MACEDONIAN, TRAIT_DRILLED],
      cost: 17,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    allies: {
      displayName: 'Allied Raw Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 5,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_ALLIES],
      cost: 13,
      options: [
        OPT_UP_PARTIAL_ARMOUR,
      ],
    },
    hoplites: {
      displayName: 'Hoplites',
      availability: CIVIS,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_DRILLED, TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR],
      cost: 18,
      options: [
      ],
    },
    veteran: {
      displayName: 'Citizen Hoplites',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: THRUSTING,
      defaultShield: HEAVY_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_SHIELD_OVERLAP, TRAIT_WALL_OF_SPEARS, TRAIT_OFFENSIVE_SPEAR, TRAIT_DRILLED],
      cost: 22,
      options: [
      ],
    },
    cavalry: {
      displayName: 'Greek Style cavalry',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_MOUNTED],
      cost: 23,
      options: [
        OPT_CHARGING,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    hetairoi: {
      displayName: 'Hetairoi',
      availability: MILITES,
      combat: 3,
      ranged: 5,
      grit: 3,
      defaultWeapon: XYSTON,
      defaultShield: NO_SHIELD,
      defaultBody: FULL,
      traits: [TRAIT_CHARGE, TRAIT_DRILLED, TRAIT_MOUNTED],
      cost: 22,
      options: [
        OPT_CHARGING,
        OPT_DOWN_PARTIAL_ARMOUR,
      ],
    },
    mounted: {
      displayName: 'Mounted Skirmishers',
      availability: RARE,
      combat: 4,
      ranged: 5,
      grit: 4,
      defaultWeapon: JAVELIN,
      defaultShield: SHIELD,
      defaultBody: NO_ARMOUR,
      traits: [TRAIT_MOUNTED],
      cost: 15,
      options: [
        OPT_DOWN_NO_ARMOUR,
      ],
    },
    elephant: {
      dontCountForBreak: true,
      displayName: 'Asian Elephant',
      availability: RARE,
      fixedFigures: 5,
      combat: 3,
      ranged: 7,
      grit: 4,
      fixedSave: '3+',
      traits: ['attacks(4)', 'wounds(5)', TRAIT_ELEPHANT],
      cost: 14.4,
      options: [
      ],
      defaultWeapon: HIDE_OPTION,
      defaultShield: HIDE_OPTION,
      defaultBody: HIDE_OPTION,
    },
    elephantCrew: {
      dontCountForBreak: true,
      displayName: 'Elephant Crew',
      fixedFigures: 2,
      availability: RARE,
      combat: 4,
      ranged: 4,
      grit: 3,
      defaultWeapon: JAVELIN,
      defaultShield: NO_SHIELD,
      defaultBody: PARTIAL,
      traits: [TRAIT_IRON_WILL],
      cost: 18,
      options: elephantOptions,
    },
  },
};

export default punic;
